### ISSUE TITLE
Chapter Ambassador MOU-like document

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4688] opened 2024-04-30 22:24 UTC
Similar to the chapter MOU, a chapter ambassador will need to sign a document via DocuSign. Add the back-end and front-end functionality to send the document to a chapter ambassador to sign.

**Comment by dboyer** [comment] 2024-05-02 15:48
Closing as a duplicate of #4697

**Closed by dboyer** 2024-05-02 15:48 UTC
Labels: ChA Onboarding
