### ISSUE TITLE
Judging Comments display null as an input

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1523] opened 2018-06-04 17:55 UTC
Comments for judges display "null" on admin side. 
Not sure if it is because judges can actually input "null" or due to another bug.
Example: https://my.technovationchallenge.org/admin/scores/15616

**Comment by Allicolyer** [comment] 2018-06-04 17:56
@joemsak this is urgent please look into this.

**Comment by joemsak** [comment] 2018-06-04 18:06
@Allicolyer Have you found these scores to actually be marked as complete?

**Comment by Allicolyer** [comment] 2018-06-04 18:07
@joemsak yes

**Comment by joemsak** [comment] 2018-06-04 18:09
@Allicolyer wow okay, will try to reproduce in a test and fix this bug ASAP with @adrichey today thanks!

**Comment by Allicolyer** [comment] 2018-06-04 18:28
So far I cannot reproduce this bug. I can't make the judging form accept "null" as an input so this must be due to something else.

**Comment by joemsak** [comment] 2018-06-04 18:47
Yeah I'm guessing that there really is a comment being written in the form but the data being saved to the score ends up being "null" somehow

The code that checks the length of the comments is only in the javascript on the browser, so it will let you finish if it sees the 40 characters, even if  -- somehow, not sure how yet -- the server is only getting 'null' in the end

**Comment by joemsak** [comment] 2018-06-04 22:56
No one is able to reproduce this bug, but @adrichey and I believe that some of the code we fixed up today might be contributing to the problem. 

We removed a feature that saves comments in the browser's localStorage (so that it can be retrieved on a page reload) because it could be the case that people are running out of this special browser storage on their device, and that would certainly return "null" into the comment box. Now, we just save directly to our server every time the user pauses in their typing.

Also, we found that the word count is not updated properly when the comment text is changed, specifically when it is deleted entirely, the word count was not being changed. So it's possible that people could have typed 40 or more words, and then their localStorage was full and replaced the comment with "null", but the word count was still 40 and the app still saw everything as valid.

So now we have a few more tests around the word count, and how/when the comment is loaded from the database. We no longer mess with the localStorage feature, so it's been taken out of the equation entirely.

The best we think we can do now, is wait for the results of these code changes on production over the next 2 days.

@Allicolyer

**Comment by Allicolyer** [comment] 2018-06-06 22:57
@joemsak so I did end up seeing this happen on QA, specifically when I was breezing through scores and copying and pasting comments.

**Comment by joemsak** [comment] 2018-06-07 13:27
Alright, @adrichey and I can try to take another look

**Comment by adrichey** [comment] 2018-06-07 14:38
I am diving into this this morning @Allicolyer. I may reach out if I am not able to replicate it on my local.

**Comment by adrichey** [comment] 2018-06-07 20:56
Potentially closed by: https://github.com/Iridescent-CM/technovation-app/pull/1526

**Comment by Allicolyer** [comment] 2018-06-08 21:20
Hey @adrichey I've stopped seeing this error on QA. It would happen when I would copy and paste comments really quickly into submissions.

**Comment by adrichey** [comment] 2018-06-08 22:03
Awesome. Sounds like my fix to the loading priority may have knocked that out. I plan on getting more tests in around that functionality next week so we can tweak things and potentially find these issues sooner.

**Comment by joemsak** [comment] 2018-06-12 13:58
@Allicolyer do you think we can close this one, or would you like to keep it up until Judging closes just in case?

**Closed** 2018-06-21 18:28 UTC
Labels: 4 - Test <= 8, [sprint topic] judging, added during sprint
