### ISSUE TITLE
Adding Judges to RPE through event invite 

### ISSUE THREAD

**Issue by danielahager** [Iridescent-CM/technovation-app#2097] opened 2019-04-12 22:32 UTC
**Describe the bug**

**To Reproduce**
Go to log in to the technovation platform, keep the tab open, go to add another judge but see there is already random people and their email addresses already added that shouldn't be. We have deleted them but then more keep appearing as judges. 

**Expected behavior**
There shouldn't be any names added to the judges sign up unless I am personally inputting their email addresses. 

**Screenshots**

**Desktop (please complete the following information):**

 - Browser: chrome

**Smartphone (please complete the following information):**

**Additional context**

**Label**
bug priority 1

**Comment by stenington** [comment] 2019-04-15 13:37
@danielahager or @kmorton2017 Can you clarify the steps to reproduce a bit more? I need something detailed enough that I can follow it step by step and see the error happening, preferably on staging.

If the error is something you're seeing on production but can't figure out how to cause on staging, please include some screenshots or videos demonstrating the issue. Thanks!

**Comment by stenington** [comment] 2019-04-15 18:51
@kmorton2017 Is this ticket the same as #2088, or a separate problem?

**Comment by stenington** [comment] 2019-04-22 18:58
Closing as a duplicate of #2088

**Closed by stenington** 2019-04-22 18:58 UTC
