### ISSUE TITLE
Support Ticket

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#3882] opened 2023-03-16 15:15 UTC
New support ticket for this iteration

**Comment by shaunxp20** [comment] 2023-03-16 19:20
>  How far a team can be from a chapter hosting an RPE before it stops showing it? For example, if teams from Vallodid (Spain) want to go to the Madrid (Spain) event, will they be able to see it? Will the chapter be able to add them?

[Original post here](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1678993964707129)

**Comment by shaunxp20** [comment] 2023-03-17 18:16
Two requests came in recently regarding email confirmations, one who didn't receive the confirmation email and another who was "stuck" on this step. For both of these here's what I did to reconstruct the email confirmation link:

- At the Rails console: `UnconfirmedEmailAddress.find_by(email: 'INSERT_EMAIL_ADDRESS_HERE')`
- Get the `confirmation_token`
- Insert the token into the email confirmation link: `https://my.technovationchallenge.org/email_confirmations/new?token=INSERT_TOKEN_HERE`

**Comment by dboyer** [comment] 2023-03-20 20:28
On QA, I created events as a ChA in Madrid and a ChA in Bilbao, Spain. I then logged in as a student in another location in Spain and was able to see events in both locations.

**Comment by dboyer** [comment] 2023-03-21 14:53
@viviancan or @shaunxp20 I looked into the question below and am going to need you to look at the code as I can't see a clear answer.

Original report:
Hi team! Testing the scores tab for score monitoring and noticed that when we use the 'live or virtual' event button and it still returns some teams that are seem to to be in RPE's. On QA the team we noticed this with is "Blanket Fort Edit" they seem to be on an event "paris power pitching" and event type "virtual" so they are placed in online judging. This is causing some confusion in score monitoring and tracking online judging stats. Also wondering if that means they will be put in the online judging pool and RPE.

My research:
I looked at the Blanket Fort Edit submission. On the admin scores page (/admin/scores#/), it appears when you filter by both virtual events or live events. It had one complete score and one incomplete score. I finished the incomplete score but that did not effect the filtering for the submission on the admin scores page. I believe both scores came from events as the judges who gave the scores were both associated with events in Paris and Blanket Fort Edit has been assigned to different Paris events during testing.

I then tried with a new submission.
1. I had the submission Madrid Minis in the general judging pool and was able to judge it as a virtual judge. 
2. I then went to the scores page (/admin/scores#/) and filtered by virtual scores. Madrid Minis appeared in the list of virtual scores and the score I added as a virtual judge was listed at /admin/score_details/507#/
3. I then assigned Madrid Minis to an event and logged in as a judge for that event. I was able to score that submission as the RPE judge. 
4. I went back to the admin scores page and filtered by "live event scores." Madrid Minis appears on the list of results. It does not appear if I filter by virtual events.
5. When I click into the scores details for Madrid Minis (/admin/score_details/507#/), it lists both the score from the RPE judge and from the virtual judge. However, the score from the virtual judge is now deleted. I did not delete it.

I think there are a few questions we need to answer:

1. If an event has virtual scores and then RPE scores, are the virtual scores automatically deleted by the platform as happened with Madrid Minis?
2. How can Blanket Fort Edit be in both the virtual and live event filters? Is this related to testing or a bug in the platform? I found that the submissions "Cactus Lovers" and "Coffee Defeats Orange Juice" are also listed both times when you filter by either virtual or live events.
3.  Is there any chance a score can have both virtual and live scores?

**Comment by shaunxp20** [comment] 2023-03-29 22:58
> @viviancan or @shaunxp20 One text change related to judge states.
> 
> Currently, the judge dashboard during semifinals references semifinals as the first round of judging. We should change the text to say:
> 
> “Welcome to the second round of online judging, also known as Semifinals! Click on the button below to open a submission and start scoring."

I updated this, it's on the way to QA. 👍

**Comment by dboyer** [comment] 2023-03-30 14:40
Confirming that I see the updated text on QA.

**Comment by shaunxp20** [comment] 2023-03-30 16:21
> 1. If an event has virtual scores and then RPE scores, are the virtual scores automatically deleted by the platform as happened with Madrid Minis?

I tried this locally and this is the behavior I'm seeing too (scores being deleted) - it looks like it's when a team is added or removed from an RPE that the team's existing virtual scores are deleted.

Steps I took: 
- I created a virtual score for a submission and then I assigned the team (and judge) to an RPE, and then the existing virtual score was deleted
- I created a virtual score for a submission that was already in an RPE, after the virtual score was completed, I removed them from the RPE and the virtual score was deleted

**Comment by shaunxp20** [comment] 2023-03-30 16:40
> 2. How can Blanket Fort Edit be in both the virtual and live event filters? Is this related to testing or a bug in the platform? I found that the submissions "Cactus Lovers" and "Coffee Defeats Orange Juice" are also listed both times when you filter by either virtual or live events.
>
> 3. Is there any chance a score can have both virtual and live scores?

From what I'm seeing the virtual/live event filter is working as intended. It looks like this is a filter for the scores - whether the score came from a virtual or live event. There is a field on the scores table called `event_type`, and for example both Blanket Fort and Cactus Lovers have scores from both "live" and "virtual" event types. So, yes to question 3 it is possible for a submission to have both live and virtual scores.

**Comment by dboyer** [comment] 2023-03-31 13:47
Thanks for the info @shaunxp20. It's super helpful.

What I'm not understanding is why a submission like Blanket Fort or Cactus Lovers can have both live and virtual scores if the virtual scores are deleted once the team is in an RPE. Or in those cases is the team in the RPE first and then moved into virtual? I suppose it would work in that case since RPE scores aren't deleted when the team is also put into virtual judging.

**Comment by shaunxp20** [comment] 2023-03-31 16:10
> What I'm not understanding is why a submission like Blanket Fort or Cactus Lovers can have both live and virtual scores if the virtual scores are deleted once the team is in an RPE. Or in those cases is the team in the RPE first and then moved into virtual? I suppose it would work in that case since RPE scores aren't deleted when the team is also put into virtual judging.

I'm not sure why they have both live and virtual scores, it might just be side effects of how we were testing on QA. Another guess (would have to be proved out) as to how this could happen is by using the manual judge assignment feature in the admin (after a team has joined an RPE).

**Closed** 2023-04-12 16:41 UTC
