### ISSUE TITLE
Write integration tests on RA event creation/management screen [13,20,0.65]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2492] opened 2020-04-24 15:30 UTC
Write integration tests for basic scenarios involving RAs creating and managing their events: creating the event, managing teams and judges, assign judges to a team, etc.

**Comment by hellafitz** [comment] 2020-07-02 20:47
- map it out collaboratively
- work it
- document anything we aren't able to tackle within the allocated effort

**Comment by shaunxp20** [comment] 2020-07-13 21:40
@stenington, when you have a moment, here's the scenarios I was thinking for this one:

RPEs:
 * creating/viewing an event
 * editing an event
 * deleting an event

Teams:
 * a team can be added to an event
 * a team can be removed from an event
 * a team cannot be added if it goes over the event capacity

Judges:
 * a judge can be added to an event
 * a judge can be removed from an event

Other scenarios:
 * printing an event
 * exporting teams to CSV
 * exporting judges to CSV

Thoughts? Thoughts on "other scenarios"? Any other scenarios we need to cover?

**Comment by stenington** [comment] 2020-07-14 14:30
I think covering that list of scenarios would be great. 

There's a feature that gets enabled if an event has 10+ teams, which is that judges can be assigned directly to teams. I believe the logic was that in big RPEs, the organizers would sometimes partition groups of judges and have them each judge a subset of submissions to limit judging fatigue. So there might be an extra set of scenarios around RPEs with 10+ submissions to assert that a judge can be assigned and un-assigned from a team. I can't remember if the interface also lets you do it from the team side.

**Comment by shaunxp20** [comment] 2020-07-15 16:11
I wrote tests for the bullet points under the headers: RPEs, Teams, and Judges in https://github.com/Iridescent-CM/technovation-app/issues/2492#issuecomment-657807468

I created a new issue (#2579) for the "Other scenarios", and for the 10+ teams scenarios.

**Comment by hellafitz** [comment] 2020-07-29 22:31
@shaunxp20 this is just an it-27 ticket, correct? I think that it-26 label slipped by us in Planning. If so, please remove.

**Comment by shaunxp20** [comment] 2020-07-29 22:40
> @shaunxp20 this is just an it-27 ticket, correct? I think that it-26 label slipped by us in Planning. If so, please remove.

It's an it-26 ticket. 👍

**Comment by shaunxp20** [comment] 2020-08-11 00:34
After so many broken builds and the ups and downs with these tests, I am finally able to get them passing on CircleCI. A couple of issues worth mentioning that I ran into:
* the configuration/env setting `MANAGE_EVENTS` controls the ability to manage judges/teams for an RPE, this was enabled locally (which I wasn't aware of initially), but wasn't enabled when running the tests through CircleCI, doh; which partially explains why they were passing locally and failing on CircleCI
* it seems rather common that tests fail [randomly](https://discuss.circleci.com/search?q=random), be [flaky](https://discuss.circleci.com/search?q=flaky), and [intermittent](https://discuss.circleci.com/search?q=intermittent) when running then through CircleCI, part of the reason is that CircleCI is slower/a shared resource vs running them locally -
["This is down to your laptop having better processing power available than the server - remember the server is shared by other users."](https://discuss.circleci.com/t/circle-ci-tests-are-failing-randomly/19858/2)
* interacting with the JavaScript library [flatpickr](https://flatpickr.js.org/) that we use to pick dates/times, this worked fine locally but failed on CircleCI - ["Where there is a difference between local and remote behaviour in web drivers like Selenium, often the issue is that you’re not waiting long enough for an element to be ready."](https://discuss.circleci.com/t/circle-ci-tests-are-failing-randomly/19858/2) - this is what I was experiencing as well; and the solution I used is in the same thread - ["I’ve found that rather than a fixed sleep (e.g. two seconds) it is better to repeatedly test the browser for something (e.g. element visibility)"](https://discuss.circleci.com/t/circle-ci-tests-are-failing-randomly/19858/2)

Anywho, finally moving this one to the Code Review column. 😄

**Comment by stenington** [comment] 2020-08-17 16:04
Makes sense, I've also written specs where I have to use assertions more for their waiting functionality than anything else.

**Comment by shaunxp20** [comment] 2020-08-26 20:07
This one is on the QA site, but QAing is not necessary, so I'm going to move this one right to the Ready to Deploy column. 😃

**Closed** 2021-02-02 01:59 UTC
Labels: 8 - Done, [theme] events, it-26, it-27, it-28, tech debt
