### ISSUE TITLE
Ask ChA to confirm they are over 18

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4537] opened 2024-02-28 21:06 UTC
Currently, we ask chapter ambassadors to provide their birth date. We would like to switch to a check box that they manually check to confirm they are over the age we set to be a chapter ambassador. The box should have the words "I confirm that I am 18 years or older."

Note: we need to see if this impacts Checkr as we may be sending the birth date to them to start the background check.

**Comment by dboyer** [comment] 2024-03-06 19:07
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4537?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment] 2024-03-14 19:38
Re: the work here should accommodate for judges and mentors to use this functionality... Maybe there's not much to that part... I'm wondering if simply adding a new `Account` level field would work, and naming it something generic like `over_required_age`, this could be used by all profiles and would safe guard against different profiles having different age requirements or having the age requirement change in the future. (The frontend would still show the actual age requirement, and the git history would have historical context for what it was set at for a given season if we ever needed it.) And then adding the field/validation which could be reused (or copied) for each profile. 🤔 

Thoughts @viviancan 🤔

**Comment by dboyer** [comment] 2024-03-14 20:07
It would be great to unify the age question as much as possible. We are good to switch to "confirm you are over 18" for judges next season but have not made that decision for mentors yet.

**Comment by viviancan** [comment] 2024-03-14 20:35
Agreed^^ @shaun-technovation I think it sounds like a great approach especially to account for potential changes with the other profile types too!

**Comment by shaun-technovation** [comment] 2024-03-20 15:55
This one is on Preview.

One thing to look out for is that since chapter ambassadors don't enter their DOB anymore, there are places in the app that are expecting a DOB, but there isn't one. So, if we find something broken w/ chapter ambassadors this might be the cause.

The "I confirm that I am 18 years or older" response isn't displayed anywhere, I guess it's assumed all chapter ambassadors on the platform meeting the minimum age requirement; we could display this field as well. Also, I added this new field second on the registration flow, right after first/last name, my thinking was that if we accidentally invite a chapter ambassador who doesn't meet the age requirement, they wouldn't fill out a bunch of fields and then realize they couldn't register (if the field was lower/later in registration). Anywho, we can change the order of this field too.

We could migrate existing chapter ambassadors to the new "I confirm that I am 18 years or older" format which would allow us to remove their DOB (which sets us up better to only collect the data we need).

Interesting note for when we add this functionality to mentors, we currently have an age check already in place (on the back-end) that checks if they are older than 14. Also, re: re-use of this functionality. I focused more on the back-end regarding this and it should allow for mentors and judges to use this functionality. For the front-end since it's in Vue, I basically just did the bare minimum to get it to work, so there won't be much to for re-use there (the way it is now it'll just be copy/paste to mentors/judges).

**Comment by shaun-technovation** [comment] 2024-03-20 16:23
Also, re: removing DOB from ChAs... DOB is needed to assign a division to an account. This *was* happening for chapter ambassadors, I didn't think chapter ambassadors needed to be assigned a division, so I removed the assignment for them. I don't think this will cause any issues, but just something to keep in mind.

**Comment by dboyer** [comment] 2024-03-21 15:57
@shaun-technovation I was able to register as a ChA and see only the checkbox rather than the birthdate. On the ChA profile, I don't see the birthdate but if I click to edit my profile, the birth date is in the form.

<img width="1382" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEw5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8f4baaabea667518dbf1140a56b5d5b512f817b3/Screen%20Shot%202024-03-21%20at%2011.56.22%20AM.png" alt="Screen Shot 2024-03-21 at 11.56.22 AM.png" />

**Comment by shaun-technovation** [comment] 2024-03-21 18:54
> On the ChA profile, I don't see the birthdate but if I click to edit my profile, the birth date is in the form.

Thanks, good catch!

Vivian also found that existing ChAs can't login (or be impersonated) b/c of the new age validation.

I have a fix for both of these.

**Comment by shaun-technovation** [comment] 2024-03-26 15:28
> > On the ChA profile, I don't see the birthdate but if I click to edit my profile, the birth date is in the form.
> 
> Thanks, good catch!
> 
> Vivian also found that existing ChAs can't login (or be impersonated) b/c of the new age validation.
> 
> I have a fix for both of these.


These two things should be fixed on Preview now. 👍

**Comment by dboyer** [comment] 2024-03-26 20:39
Checked on preview and confirmed:

- I can register a new account and am just asked to confirm I'm over 18 and not enter birthdate
- I do not see birthdate as an option when I'm editing my profile
- I was also able to impersonate an existing ChA
- I logged in as a returning ChA and could access my profile and make edits

**Comment by shaun-technovation** [comment] 2024-04-16 21:39
Also, noting here that the judge over 18 work is now on Preview too, which I had to resolve some conflicts to bring the ChA and judge over 18 work together, so just a heads up if anything seems off.

**Comment by dboyer** [comment] 2024-04-17 14:18
Tested on preview and was able to sign up as a judge by checking the box and not entering my birthdate. I then added the birthdate on the profile and it saved as expected. I was also able to sign up as a ChA.

I did see a "null" tag on the sidebar for the judge profile which I hadn't seen before. Not sure if this is related or not.
<img width="444" alt="Screen Shot 2024-04-17 at 10 13 53 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/b1384156-a79b-4d31-9c13-a6e3bc04f81b">

**Closed** 2024-08-15 14:49 UTC
Labels: 🏖 Chapter Ambassadors ⛺️, AmeriCorps, ChA Onboarding
