### ISSUE TITLE
Copy for registration emails, honor code, and description of a qualified team need to be updated by October 1st.

### ISSUE THREAD

**Issue by Allicolyer** [Iridescent-CM/technovation-app#1647] opened 2018-08-31 16:53 UTC
All copy for emails link <a href="https://docs.google.com/document/d/1HWSakYAvF7x7NilTa-aI5Bru-lO8rvoR5iiNSux0RsY/edit"> here </a>
<ol>
<li>Student Welcome email needs to be updated</li>
<li> Mentor Welcome Email needs to be updated </li>
<li>Email to Parent to complete consent form (looks good to me) copy 
<li>Parent consent form needs to update</li>
<li> Mentor consent form </li>
<li> 2018 Honor Code needs to be updated</li>
<li> Volunteer consent Form needs to be updated </li>
<li> Pop-up for what is a qualified team has content that needs to be simplified </li>
</ol>

Madhavi and Katie will give us the go ahead once the copy has been updated.

**Comment by Allicolyer** [comment] 2018-09-04 17:35
@madhavitechnovation and @kmorton2017, just as a reminder, please Slack me or add to this thread when this text is ready to go!

**Comment by madhavitechnovation** [comment] 2018-09-05 15:56
@Allicolyer will have the updated versions ready this week

**Comment by Allicolyer** [comment] 2018-09-05 17:58
Thank you @madhavitechnovation!

**Comment by kmorton2017** [comment] 2018-09-05 21:19
@madhavitechnovation @amyiridescent the lawyers are reviewing the parental consent form and volunteer consent form right?

**Comment by kmorton2017** [comment] 2018-09-27 16:41
Here is the link to all of the updated automatic email copy: https://docs.google.com/document/d/1HWSakYAvF7x7NilTa-aI5Bru-lO8rvoR5iiNSux0RsY/edit?ts=5bac5761

**Comment by Allicolyer** [comment] 2018-09-27 19:35
@joemsak @adrichey we are good go to on all of this copy. do you guys need help formatting it?

**Comment by joemsak** [comment] 2018-09-28 15:48
@Allicolyer besides the consent waiver copy (I have asked for the specific changes on that one) I have updated all of these

**Comment by joemsak** [comment] 2018-09-28 18:02
@kmorton2017 confirmed no change to consent waiver, this is ready for QA!

**Comment by joemsak** [comment] 2018-09-28 20:27
@madhavitechnovation thank you, that is all expected, because the emails are coming from QA, however our marketing site has been hardcoded into the email

@kmorton2017 yes, every single time you ever see the year in any page, any email, any anywhere, yes it will change to correct season year automatically

as for the link, okay, I copied the one that was linked in the google doc so if that wasn't correct please update it

**Comment by joemsak** [comment] 2018-09-28 20:29
@kmorton2017 sorry, i understand you now, it is not linked at all. fixing ASAP please be ready to come back to QA this card again

**Comment by joemsak** [comment] 2018-09-28 20:35
@kmorton2017 this is ready for QA again

**Comment by kmorton2017** [comment] 2018-09-28 21:39
When someone receives a join request email, it currenlty says: 

"Please take a minute to approve or decline the mentor request within the next week so that Layla can reach out to another team if needed."

It should say "within the next two weeks."

**Comment by joemsak** [comment] 2018-09-28 21:42
@kmorton2017 you're right, and I had totally checked that and completely overlooked it. it will be fixed ASAP - please be ready to QA again

**Comment by ophelieh** [comment] 2018-10-02 19:53
When a student or mentor are asked to join a team, this is what I get: 


![uploads/678a1ce1-9702-449f-b400-693d2d33d007/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F678a1ce1-9702-449f-b400-693d2d33d007%2Fimage.png)

Does that mean we removed the time frame?

**Comment by joemsak** [comment] 2018-10-02 20:01
@ophelieh the copy being checked is for when a mentor asks to join a team - so send a join request as a mentor to a team, then check for the 'two weeks' line. thanks!

**Comment by ophelieh** [comment] 2018-10-02 21:08
OK. Looks good!

**Closed** 2018-10-03 19:08 UTC
Labels: 5 - Test <= 8
