### ISSUE TITLE
Add "mentor types" field on admin participants page

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4030] opened 2023-06-14 17:21 UTC
The participants page in the admin needs to be updated to allow admins to select multiple mentor types and view the corresponding mentors of those types.

**Background info:**
Mentors are now allowed to select multiple mentor types (#4013). From this work, the mentor type selection on the participants page in the admin was temporarily removed.

**Comment by dboyer** [comment] 2023-06-21 17:39
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4030?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment] 2023-06-21 19:42
Confirmed with VET that this should be an OR type search. Adding multiple mentor types to a search should return results that meet any of the search terms NOT only those that meet all search terms.

**Comment by dboyer** [comment] 2023-07-03 15:26
Confirmed on QA that I can add mentor types as an additional column. Added several different types of mentors and confirmed the search returned those that matched any of the selected search terms.

**Comment by dboyer** [comment] 2023-07-06 17:23
@viviancan One potential wrinkle based on testing from VET. Rae's testing found:

1. Search for two mentor types (i.e. postsecondary student and alumna)
2. Results return people who have either (or both) of those mentor types. In the mentor type column, it shows postsecondary student, alumna, or postsecondary student and alumna
3. In the export of search results, the mentor type column includes postsecondary student, alumna, or postsecondary student and alumna

The issue is that if a mentor is a postsecondary student and/or alumna but also has another mentor type (i.e educator in the case of /admin/participants/1087#/), that educator mentor type does not appear anywhere in the search result grid or the export. VET would thus have inaccurate information on the full list of mentor types for that user.

Ideally, all mentor types for the mentor would be in the mentor type column and exported. So search by the selected mentor types but display all mentor types for the mentor.

**Comment by viviancan** [comment] 2023-07-10 15:56
Moving this back into code review! [This PR](https://github.com/Iridescent-CM/technovation-app/pull/4093) addresses the issue

**Comment by viviancan** [comment] 2023-07-11 20:26
Confirming the update is on QA

**Comment by dboyer** [comment] 2023-07-12 14:40
Confirming that I also now see all mentor types for an individual (not just the ones searched) and all types are included in the export.

**Closed** 2023-07-19 16:53 UTC
Labels: 🏖 Admin ⛺️
