### ISSUE TITLE
Allow judges to see past round scores (but not edit)

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1104] opened 2017-06-26 20:29 UTC
QA Instructions

1. Change the judging round to "semi-finals"
2. Log in as a judge who has quarterfinals scores
3. Click on "quarter finals" on the dashboard to review quarterfinals scores.

**Comment by Allicolyer** [comment] 2018-05-24 20:39
@joemsak does this not already work?

**Comment by joemsak** [comment] 2018-05-24 20:45
Could QA it real quick

**Comment by Allicolyer** [comment] 2018-05-24 20:48
@kmorton2017 @ophelieh could you guys also QA this :)

**Comment by ophelieh** [comment] 2018-05-25 18:21
Looks good, one thing I would change is the wording for the quarterfinal scores. Could we say "View your QF scores" instead of "review your QT scores"? It makes it sound like you could edit your score for the previous round.

**Comment by joemsak** [comment] 2018-05-29 16:00
Thanks @ophelieh and @Allicolyer - take another look today

**Comment by joemsak** [comment] 2018-05-30 13:47
Yeah sorry that's the public version of the submission page so it doesn't
have those links cos it doesn't know if you're a student or whatever, it
doesn't expect anyone to be logged in

**Comment by joemsak** [comment] 2018-05-30 14:01
The public submission link will now open in a new window, and the text has been updated as requested

**Comment by ophelieh** [comment] 2018-05-30 19:34
Looks great! Thank you!

**Comment by Allicolyer** [comment] 2018-05-31 21:37
hey @joemsak ! I noticed that judges can see the code checklist on this public page. 

Judges were not able to see this in the first round of judging, but now they can see it when reviewing the submission? I worry this may cause confusion. Can you remove this from the judge's public page or from the public page all together? It is not really relevant anyway.

**Comment by joemsak** [comment] 2018-05-31 21:39
it's going to look pretty empty and less impressive without it and really
it's just there for convenience to remind them why they gave the scores
they did in QF if they even bother to look at any of that stuff

Joe Sak
Technovation Web Development

SMS
+1 (312) 945-6317

**Comment by Allicolyer** [comment] 2018-05-31 21:42
@joemsak I am worried about judges emailing us say that they did not see the code checklist and would have given a different score if they had seen it.

**Comment by Allicolyer** [comment] 2018-05-31 21:43
@joemsak I think this group of judges will bother to look at it -- they are very committed and intense

**Comment by joemsak** [comment] 2018-05-31 21:45
okay then the easier thing to do is just remove the link because that is
the only public page there is, that everyone else uses

Joe Sak
Technovation Web Development

SMS
+1 (312) 945-6317

**Comment by Allicolyer** [comment] 2018-05-31 21:48
okay I think that is the best decision. @ophelieh what do you think?

The issue is the public submission pages that judges can see for their quarterfinals scores contain code checklists, and the judges have never seen those before.

I worry it is going to cause a flurry of emails if judges find out that some girls wrote gibberish or lied on their code checklist (and with these judges I think that this will happen).

I would prefer to remove the public page to avoid this issue.

**Comment by Allicolyer** [comment] 2018-05-31 22:28
@amyiridescent thinks these public pages might get weird with the new EU law.

**Comment by amyiridescent** [comment] 2018-05-31 22:40
Yeah I am not sure legally if we are allowed to create public links that can be shared with videos links that might feature their names and faces based on the new EU law. We are awaiting legal help on how we should interpret the law for our program... It might be better to not give judges the option to get "public links" and only view submission elements from our website. I know technically, they can still share the youtube links but at least they need to do that intentionally...

**Comment by joemsak** [comment] 2018-06-01 14:59
the links have already been removed for judges

**Comment by Allicolyer** [comment] 2018-06-01 16:52
:thumbsup:

**Closed** 2018-06-01 16:52 UTC
Labels: 4 - Test <= 8, [sprint topic] judging
