### ISSUE TITLE
Bug: The "can be marked onboarded" method for ChA onboarding status does not account for background check exemptions

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4963] opened 2024-08-20 17:19 UTC
Currently, if you grant/revoke a background check exemption, the ChA onboarded status is not updated.

For ex, if you grant a bg check exemption and all other onboarding tasks are complete the ChA will see 8 green checkmarks. When they click on "Chapter Admin Activity" they get the error message even though they have completed all ChA and Chapter onboarding steps. This happens because the onboarded method which updates the ChA onboarded status does not account for bg check exemptions (it currently only checks for "completed" bg checks).

**Comment by viviancan** [comment] 2024-08-21 00:46
This is on QA

**Comment by dboyer** [comment] 2024-08-21 15:16
Tested on QA:

- Logged in as a ChA and completed all onboarding steps except background check
- Confirmed I could not access the chapter admin activity
- As an admin, I gave a background check exemption to that ChA
- Logged back in as the ChA and did not have access to the admin activity

@viviancan This was testing with /admin/participants/2067#/

**Comment by dboyer** [comment] 2024-08-21 17:28
Tested again and this is working for other participant ChAs. The ChA that did not work appeared due to a chapter onboarding flag not updating correctly. We edited the chapter summary to force a reload of the record and the chapter was then marked as onboarded and the ChA could access their chapter admin activity.

**Closed** 2024-09-04 16:49 UTC
Labels: bug
