### ISSUE TITLE
Printable event page can show judges no longer in the event

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2043] opened 2019-03-15 13:46 UTC
**Describe the bug**
The RA events view and printable view can show a different set of judges for an event.

**To Reproduce**
1. Login as Neil Degrasse Tyson
2. Go to events
3. Look at Judge Test Cap, note the 3 teams and 1 judge
4. Click the "Print for live event" icon
5. See only 2 teams and 4 judges

**Expected behavior**
@ophelieh @kmorton2017 Can you help fill in the expected behavior here? I assume I should see all partial and complete scores only related to the teams and judges currently assigned to the event, right?

**Additional context**
I assume a big factor here is that our staging data has gotten very messy. Hopefully in production we won't have quite the craziness with teams and judges being assigned, unassigned, scored, assigned again, etc. But nevertheless I think the printable view should be able to handle some of these potential scenarios.

**Comment by ophelieh** [comment] 2019-03-19 15:22
Expected behavior - As an RA, I only see judges currently assigned to my event. I should also see their partial or completed scores.

**Comment by adrichey** [comment] 2019-03-22 15:41
@ophelieh and @kmorton2017 I have a question about this. For the particular event that is listed in the description, we have various other judges that have judged the teams at some point due to the ever-shifting way we do our QA, so if you look at the Scores section for that RA, we get results that don't match the printable view if I put a fix in place.

Print out:
[printable_scores.pdf](https://github.com/Iridescent-CM/technovation-app/files/2997193/printable_scores.pdf)

Actual scores:
https://technovation-qa.herokuapp.com/regional_ambassador/score_details/83#/
https://technovation-qa.herokuapp.com/regional_ambassador/score_details/88#/

What do we want to do about this? Is there anything to be done? Can you give me more information on how we handled this in the past? I have a fix for this ticket, but I want to make sure I have a full picture of this before I submit my work.

**Comment by ophelieh** [comment] 2019-03-25 13:38
Should we create a new event to get some better data? @kmorton2017 Could you create an event, add some teams and have Nick and Kai score some submissions? At least 1 partial and 2 complete would be good. 

Also, I noticed that there are a lot of blank pages on the PDF, is that normal?

**Comment by adrichey** [comment] 2019-03-25 15:32
The blank pages is not normal, I planned on tackling that, I just wanted to get this in front of you both so you could provide feedback on the scenarios I mentioned previously. Thanks! 🙂

**Comment by ophelieh** [comment] 2019-03-25 15:57
Perfect. Thank you!

**Comment by adrichey** [comment] 2019-03-27 15:21
@ophelieh and @kmorton2017 I am also a bit confused as to what this page is supposed to be. Right now it is a page where any scores for a team show up. This is not the functionality desired according to this ticket description. That being said, I am confused on how to actually fix this. Do we want to display a scoring page for each judge/team combination? That way they can record scores on the sheet and then fill them out online later? Because right now, it only pulls scores already in the system, which seems like that is not what was desired from this functionality. I am marking this ticket as blocked until I get feedback from you as I don't understand what this is used for exactly.

**Comment by adrichey** [comment] 2019-04-03 17:28
@ophelieh and @kmorton2017 I thought I would tag you again so that you could take a look at my questions from before about this ticket so we can get started on it again. Any light you can shed would be appreciated. Thanks!

**Comment by kmorton2017** [comment] 2019-04-10 19:49
Hi Alan,

Here is some context for this ticket. The printable score sheets serve as a way for judges who inputed their draft scores in already online to easily reference them during the event, and for them to mark up/edit their scores. Some people prefer to have a paper sheet for them to write on and organize their thoughts quickly. Others may struggle connecting to the Internet in low bandwidth areas to change their scores and need a paper record. A paper copy also serves as a good record for us in case confusion happens at the event and need to determine a winner. 

Ideally each page would have the judge and their incomplete or completed scores. If they have not scored the team at all, then it would be blank. 

As an organizer of the event, I would be able to easily hand the judge a page for each of the teams for them to use.

**Comment by adrichey** [comment] 2019-04-10 21:52
@kmorton2017 Okay, got it. This is very helpful.

**Comment by adrichey** [comment] 2019-04-11 14:51
@kmorton2017 I am still confused on this. When you say:
> Ideally each page would have the judge and their incomplete or completed scores. If they have not scored the team at all, then it would be blank.
Are you referring to a blank scoring sheet for that team, or an omitted score sheet?

**Comment by stenington** [comment] 2019-04-11 14:57
Blank scoring sheet. 

I kind of remember this now. I think the use case is that the web app doesn't always work well at RPE venues, and judges need to judge fast. So if each judge can have a printout of a scoring sheet to use, that's easier. And then if the judge started or even completed a score ahead of time, it's nice for them to have a printout showing the previous numbers they chose for them to edit if they change their minds during the actual pitch. I think these sheets are either then entered by each judge after the event, or sometimes I think even the RA entered them or something?

**Comment by adrichey** [comment] 2019-04-11 14:58
Right on. I don't think the logic ever accounted for that. It was only displaying the sheet if they had already started or completed a submission. So I am going to have to suss out the best way to do this in that case.

**Comment by stenington** [comment] 2019-04-11 15:00
Yeah, plus some events assign judges and others don't and have all judges judge all submissions, so you need to account for that too.

**Comment by adrichey** [comment] 2019-04-11 15:00
Yeah, I am going to address the easier of the two scenarios where there are no assignments and then circle back to that. Thanks Mike.

**Comment by kmorton2017** [comment] 2019-04-11 18:25
yes @stenington is correct. small correction-RA's are not allowed and the system does not permit them to enter scores but it is useful for judges to use to input afterwards on their account.  If you would like an RA's perspective Jean Weiss would be a good person to ask.

If this is becoming too much of a beast though then don't worry. we don't have to prioritize it. i'm seeing a lot of back/forth on the QA channel.

**Comment by stenington** [comment] 2019-04-15 19:44
@kmorton2017 This is in staging, but I'm having trouble putting together QA steps because I realized I don't actually know what's supposed to happen for teams in an event marked as "Submission in progress" or "not qualified". Can I leave this to you to write QA steps for, or do we need to talk further about how the printable view feature is supposed to work?

**Comment by stenington** [comment] 2019-04-15 20:09
On second thought, here's some basic QA steps that would get us started. It may not catch all the edge cases though.

1. Log in as an RA
2. Go to events
3. Create a new event
4. Add 3 teams
5. Add 3 judges
6. Click the "Print for live event" icon
7. Confirm that each judge has a score sheet for each team (9 score sheets total)
8. If any of the judges have already judged any of the teams, ensure their existing scores have been pre-populated on their score sheet

and then 

1. Log in as an RA
2. Go to events
3. Create a new event
4. Add 10+ teams
5. Add 4 judges
6. Assign the same 2 judges to judge the same 5 teams
7. Assign the other 2 judges to judge the other 5 teams
6. Click the "Print for live event" icon
7. Confirm that each judge has a score sheet for their assigned teams (20 sheets total)
8. If any of the judges have already judged any of the teams, ensure their existing scores have been pre-populated on their score sheet

**Comment by stenington** [comment] 2019-04-15 20:32
I tried following my own QA steps on events that already existed in staging, and the results seemed very messy. However when I created new events it seemed to work much better, so I have a suspicion that some of our old events have gotten a bit messed up over time (judges assigned to the event multiple times and the like) and I'm hoping our production data will be cleaner.

**Comment by ophelieh** [comment] 2019-04-16 17:53
@nickiredescent Could you test this? I'll try to test as well. Thank you!

**Comment by nickiredescent** [comment] 2019-04-17 21:28
Tested both scenarios. Can confirm that this feature works as described, including previously existing scores showing up on the printable sheet.

**Comment by kmorton2017** [comment] 2019-04-17 22:26
Everything works as expected for both scenarios.

**Closed** 2019-04-17 22:28 UTC
Labels: 6 - Done, [sprint topic] events, bug
