### ISSUE TITLE
Apply new styles to location interrupt screen

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3251] opened 2022-02-10 18:46 UTC
As a student, I need to update my location in order to access the dashboard.

Currently, the box that shows up has a mix of old and new styles

![Screen Shot 2021-11-30 at 10.18.15 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/9dc9dc46-91c5-4126-a05e-e68aa0a41e8f)

Task: Apply new styling conventions and fix the size of the input fields
![Screen Shot 2022-02-10 at 10.51.51 AM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/38744d59-c8d9-4b0d-b997-6a9d6be748f4)

**Comment by rsgonzal** [comment] 2022-03-14 04:36
- [ ] Mentor or judge visits my profile and edits location
<img width="1165" alt="Screen Shot 2022-03-13 at 9 32 01 PM" src="https://user-images.githubusercontent.com/22801026/158105383-c20673bd-426e-4c21-9f51-228ff6d8d46c.png">

- [ ] Check team location as a student

<img width="844" alt="Screen Shot 2022-03-13 at 9 36 19 PM" src="https://user-images.githubusercontent.com/22801026/158105663-65b4f5ac-6350-44ca-98c6-c34821d560e7.png">

**Comment by devkonrad** [comment] 2022-03-14 11:22
> There are a few places where styles are broken, we can start with the last one in this list that affects students.
> 
> Let's chat tomorrow on the best way to approach mentor & judge views.
> 
> * [ ]  Mentor or judge visits my profile and edits location
> 
> <img alt="Screen Shot 2022-03-13 at 9 32 01 PM" width="1165" src="https://user-images.githubusercontent.com/22801026/158105383-c20673bd-426e-4c21-9f51-228ff6d8d46c.png">
> 
> * [ ]  Signing up as mentor or judge
> 
> <img alt="Screen Shot 2022-03-13 at 9 39 36 PM" width="1160" src="https://user-images.githubusercontent.com/22801026/158106026-4b8aadea-6337-4338-a2d5-8eed73aa300f.png">
> 
> * [ ]  Check team location as a mentor
> 
> <img alt="Screen Shot 2022-03-13 at 9 32 01 PM" width="1165" src="https://user-images.githubusercontent.com/22801026/158105779-db4cf3f3-b6e8-48b3-8dd0-c9c25cb05e06.png">
> 
> * [ ]  Check team location as a student
> 
> <img alt="Screen Shot 2022-03-13 at 9 36 19 PM" width="844" src="https://user-images.githubusercontent.com/22801026/158105663-65b4f5ac-6350-44ca-98c6-c34821d560e7.png">

Hi, @rsgonzal! I will take a look on these problems!

**Comment by devkonrad** [comment] 2022-03-14 12:45
![Captura de tela de 2022-03-14 09-41-43](https://user-images.githubusercontent.com/99268176/158174321-631107fe-ebe2-44c5-946e-09eb4648db71.png)
Hi @rsgonzal , i tested the Student Screen on QA environment, and it looks fine for me. Wich resolution you are using? Maybe its necessary to clean you local cache.

**Comment by devkonrad** [comment] 2022-03-14 12:48
> ![Captura de tela de 2022-03-14 09-41-43](https://user-images.githubusercontent.com/99268176/158174321-631107fe-ebe2-44c5-946e-09eb4648db71.png) Hi @rsgonzal , i tested the Student Screen on QA environment, and it looks fine for me. Wich resolution you are using? Maybe its necessary to clean you local cache. Someone else is seeing this page with wrong width?

**Comment by dboyer** [comment] 2022-03-14 13:47
@devkonrad I think you and Rox are looking at different screens.

If you go to my profile as a logged-in student, and then select the location option in the "profile settings" box in the left sidebar, you get the location screen you posted. Everything is styled and the correct width.

If you are logged-in as a student and already have a team, select "my team" from the tabs at the top and then "my location" from the list of options in the "my team" menu in the left sidebar. That opens the location selector that is not the correct width.

<img width="688" alt="Screen Shot 2022-03-14 at 9 44 01 AM" src="https://user-images.githubusercontent.com/516764/158184582-4752f4a7-7cf5-481a-83da-644aa5926497.png">

**Comment by devkonrad** [comment] 2022-03-14 13:51
> @devkonrad I think you and Rox are looking at different screens.
> 
> If you go to my profile as a logged-in student, and then select the location option in the "profile settings" box in the left sidebar, you get the location screen you posted. Everything is styled and the correct width.
> 
> If you are logged-in as a student and already have a team, select "my team" from the tabs at the top and then "my location" from the list of options in the "my team" menu in the left sidebar. That opens the location selector that is not the correct width.
> 
> <img alt="Screen Shot 2022-03-14 at 9 44 01 AM" width="688" src="https://user-images.githubusercontent.com/516764/158184582-4752f4a7-7cf5-481a-83da-644aa5926497.png">

Thank you, @dboyer!! I will take a look in that screen!

**Comment by rsgonzal** [comment] 2022-03-23 06:19
The only screen that I see messed up is the judge editing my profile. This is probably because vivian just updated. I am guessing whatever fixed the student one, will apply to judges. Not sure if @viviancan wants to tackle because she is in these pages?

![Screen Shot 2022-03-22 at 11.16.09 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/384cc19d-4908-4931-8b94-eca622cbf100)

**Comment by devkonrad** [comment] 2022-03-23 12:36
> The only screen that I see messed up is the judge editing my profile. This is probably because vivian just updated. I am guessing whatever fixed the student one, will apply to judges. Not sure if @viviancan wants to tackle because she is in these pages?
> 
> ![Screen Shot 2022-03-22 at 11.16.09 PM.png](https://camo.githubusercontent.com/fd472a60e5bb073eb18c6fb7a97c8cb83a6590441cf636a1b4096d20b97e77ed/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630353237313639636465323737323234326430646539352f33383463633139642d343930382d343933312d386239342d656361363232636266313030)

Hi, @rsgonzal and @viviancan ! I just fix this screen and published it on QA environment already.

**Comment by viviancan** [comment] 2022-03-23 14:10
Hi @devkonrad I see the updates to the location fix on QA! Looks great. Are you able to apply the same fix to the "Change your basic profile details" in the judge "My Profile" > Basic Information

<img width="1442" alt="Screen Shot 2022-03-23 at 9 07 55 AM" src="https://user-images.githubusercontent.com/29210380/159718535-50892769-7485-4d78-8f76-c4fe4d459966.png">

<img width="1607" alt="Screen Shot 2022-03-23 at 9 05 10 AM" src="https://user-images.githubusercontent.com/29210380/159718589-f69f5c8f-c5bb-4644-9e88-930170ebf8f4.png">

See issue #3302

**Comment by dboyer** [comment] 2022-03-23 15:21
This is a small thing but could we make "Cancel" be capitalized on the button in the location setting screen so that it matches Save, Next, Back, and all the other buttons? @devkonrad

**Comment by dboyer** [comment] 2022-03-25 15:36
@devkonrad It looks like the formatting for the "Confirm your region" screen in the location interrupt process is left aligned and narrow rather than extended across the full screen space. Could you adjust that?

<img width="1315" alt="Screen Shot 2022-03-24 at 8 31 06 PM" src="https://user-images.githubusercontent.com/516764/160152365-189b9ad1-9243-4155-9121-3d1354440a79.png">

**Comment by rsgonzal** [comment] 2022-03-29 19:02
@devkonrad hey alex! Saw something go through github, did you make an update to this?

**Comment by devkonrad** [comment] 2022-03-29 20:40
> @devkonrad hey alex! Saw something go through github, did you make an update to this?

Hi, @rsgonzal ! I was trying to reproduce this problem locally, but here everything looks ok. I talk with @viviancan about it and looks like she have the same problem. I purpose a solution and put the PR on github for discution.

**Comment by rsgonzal** [comment] 2022-03-29 22:35
Thank you!! Very strange it's not happening there. We can talk about it tomorrow.

**Comment by dboyer** [comment] 2022-04-07 15:26
No additional issues found during testing so moving this to ready to deploy

**Closed** 2022-05-09 02:35 UTC
Labels: good-first-issue, 🏖 Dashboard/Onboarding ⛺️
