### ISSUE TITLE
Confirm/create rake task for setting semifinalists

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2050] opened 2019-03-21 17:16 UTC
The idea here is that the program team would provide us a spreadsheet listing all of the teams/submissions that are moving on to the finals, and we'd have a rake task to read that file and update each submission's contest rank in the database.

Step 1 is probably figuring out what that spreadsheet might look like, and whether it has team IDs or submission IDs. 

The task should **complain very loudly** if it encounters any problem along the way, e.g. can't find an id. It might be nice for it to generate a human-readable list of the teams/submissions it updated as well for double-checking, although I believe we also plan to have people double-check through the admin.

**Comment by adrichey** [comment] 2019-04-08 14:49
I went ahead and tested this ticket since it does not have an associated UI element. It is working as intended. Closing the ticket.

**Closed by adrichey** 2019-04-08 14:49 UTC
Labels: 4 - In Progress <= 6, [sprint topic] scores / certs
