### ISSUE TITLE
Do not automatically opt-in mentors to the "connect to mentors" platform

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#3249] opened 2022-02-02 15:28 UTC
Currently, mentors are automatically opted in to "allow other mentors to find you in search results and connect via email" via a check-box on their profile (/mentor/profile#!basic).

We should remove the default check-box so that mentors have to choose to opt-in to having their info shared with other mentors. The other two boxes can be checked by default as they are used for team matching and do not share email addresses with other users.

<img width="670" alt="Screen Shot 2022-02-02 at 10 28 23 AM" src="https://user-images.githubusercontent.com/516764/152184361-30659d78-3662-4608-b6a3-246a727544b5.png">

**Comment by dboyer** [comment] 2022-08-03 17:29
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/3249?planning-poker) with ZenHub @devkonrad @shaunxp20 @viviancan

**Comment by devkonrad** [comment] 2022-08-09 18:26
Created PR https://github.com/Iridescent-CM/technovation-app/pull/3580 to tackle with this issue. ;)

**Comment by viviancan** [comment] 2022-09-14 21:45
QA Steps
1. Register as a new mentor
2. Complete mentor onboarding (location, training, & consent waiver)
3. View mentor profile by clicking "Profile" link in subnav
4. Verify the "Allow other mentors to find you in search results..." checkbox is not checked

**Comment by viviancan** [comment] 2022-09-15 13:12
@dboyer @shaunxp20 

GM! Something very strange is happening with the "accepting team invites" field. When a new mentor is created, the correct process is happening where "connect with mentors" is automatically set to false. However, I noticed (and verified in the DB on QA) that the "accepting team invites" field is now automatically being set to false as well - which is what we don't want! The strange part is that locally this behavior is not replicated and the PR I made does not alter the "accepting team invites." Unfortunately, I am not sure if this change caused that to happen or if it was an existing change. 

I checked the DB and there were 3 mentor accounts created between this change and previous PRs. I also cross-referenced those accounts with the "activity tracker" table and what's interesting is there is 1 mentor account where it looks like the "accepting team invites" field was automatically set to false because there is not an associated logged activity. When you update the searchable checkboxes an update activity gets logged. So it kind of seems like this could be related to something else? The other 2 accounts have the associated account updated logged. A lot of ifs here 🤔

i just created a "revert" PR to undo the change which could be 1 approach to verify. Maybe Shaun could try it locally as well? Or we could turn on registration on prod for a few seconds to register as a test mentor and check if the "accepting team invites" is being set to false automatically (if so, then this would be related to something else). I think what makes this tricky is that the behavior is not happening locally so it is difficult to pinpoint what is causing this. I even checked the ENV variables for some sort of setting, but didn't see anything.

**Comment by dboyer** [comment] 2022-09-15 13:52
Oh that is super odd that the two fields of connect with mentors and accept team invites seem to be linked on QA and not locally. I'm okay with turning on prod to register a mentor quickly if we need to, but we'll need to give PT a heads up that the mentor count might be different than expected.

Also, if this is getting more complex, we can shelve this task for awhile. We need to fix it eventually but if it's bigger than expected, it can wait in favor of the photo and registration work.

**Comment by viviancan** [comment] 2022-09-15 14:58
Moving this back to code review, there is a pending ["revert" PR ](https://github.com/Iridescent-CM/technovation-app/pull/3633). Once reverted I can verify/compare the behavior on QA!

**Comment by viviancan** [comment] 2022-09-15 18:27
Changes were reverted but when signing up as a new mentor the accept team invites is still defaulting to false and the connect to mentor is still defaulting to false (before it was true). I am adding a blocked label on this because I am really unsure of where to go from here!

**Comment by viviancan** [comment] 2022-09-15 20:21
This issue has been resolved! SO to Shaun for talking it out! An additional migration was created in order to reset the connect_with_mentor default value back to true. This was needed bc even though the previous PR had been reverted the DB didn't rollback automatically! 

After checking on QA, when a new mentor completes onboarding they are automatically opted in to the "connect with mentors" (the old behavior) but something new has popped up. They are also automatically set to "not accept team invites" - which is what we do not want. I've spent a good amount of time troubleshooting this issue, but I think it could definitely be its own ticket now! 

At this point, we need to decided how to proceed with the "connect with mentors" option. Should we wait until later to add that back in or add the migration again now before the season opens so mentors will not automatically be opted in to connect with other mentors?

**Comment by viviancan** [comment] 2022-09-29 21:26
Confirming the latest [PR 3665](https://github.com/Iridescent-CM/technovation-app/pull/3665) worked and this is working as expected on QA.

**The expected behavior**: A mentor registers, completes training and signs the consent waiver. When they visit their profile they should **not** be opted in to connect with other mentors by default. The 3rd checkbox should be unchecked.

**Comment by dboyer** [comment] 2022-10-04 14:43
On QA, I registered as a new mentor and completed all the training/waiver steps. When I went to my profile, the "ALLOW OTHER MENTORS TO FIND YOU IN SEARCH RESULTS AND CONNECT VIA EMAIL" box was not checked.

I logged in with another mentor account and then went to the "connect to mentors" section. I searched for the first account that had not opted in and could not find it.

**Closed** 2022-10-12 17:41 UTC
Labels: good-first-issue
