### ISSUE TITLE
Rebrand: full TG favicon, titles, and metadata [it-05 *,8,*]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2172] opened 2019-08-28 20:59 UTC
This comes from https://github.com/Iridescent-CM/curiosity-machine/issues/2286

We want to update favicons, page titles, and any open graph or other meta tags that reference Technovation Challenge or old branding graphics to their newer counterparts.

### Social share copy:

Join 20,000+ girls who are changing the world using technology.

*Characters used: 63*

![FB_Link_TG-2016-WP_JJCasas-397](https://user-images.githubusercontent.com/6475595/62067401-81387280-b1e8-11e9-84a8-ed0325c32a66.png)

### SEO:

**Technovation Girls**
Join 20,000+ girls around the world who are solving real problems using technology. Learn how to code, market, and pitch a mobile app and business with Technovation Girls.

**Comment by stenington** [comment] 2019-09-03 19:01
@rsgonzal This is ready to talk about a test plan.

**Comment by hellafitz** [comment] 2019-09-04 19:28
Test plan
- turn off the ENABLE_REBRAND config toggle. It should only turn off the banner (not the other rebrand updates)
- check the Fb preview for the site using https://developers.facebook.com/tools/debug/sharing/
- check how the site shows up in search using Mike's tool from https://github.com/Iridescent-CM/curiosity-machine/issues/2301

**Comment by stenington** [comment] 2019-09-05 19:45
@rsgonzal I noticed while QAing the other ticket that the logo is missing in staging right now. Let me fix that glaring issue before others do their poking around.

**Comment by stenington** [comment] 2019-09-05 20:08
@rsgonzal Ok, fix is on the way to staging.

**Comment by rsgonzal** [comment] 2019-09-07 00:05
- Favicon doesn't show up when logged in as admin, but there isn't one in production either
- I'm still getting the wrong preview on the Facebook debug tool, it kind of looks like it's pulling the images from the production site even though i put in staging site

**Comment by stenington** [comment] 2019-09-09 13:42
@rsgonzal For the first part, I was doing a search-and-replace so if production doesn't have a favicon in the admin it makes sense that staging wouldn't either. For the second part, it looks like staging was pointing to production as the "source of truth" for stuff like the share image, so I fixed that and I think it's working now: https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Ftechnovation-qa.herokuapp.com%2F

**Comment by rsgonzal** [comment] 2019-09-10 00:24
- RA page also doesn't have logo, never had i imagine
- the social icons at the bottom are wrong, is this within the scope of this ticket?

Otherwise I think the right logos are where they should be

**Comment by rsgonzal** [comment] 2019-09-10 23:05
If so, here are the links from katy:
- twitter.com/technovation 
- facebook.com/technovationglobal
- instagram.com/technovationglobal 
- https://www.linkedin.com/company/technovation
- https://www.youtube.com/channel/UCvxNjrhfz_M68fwT2QcurjQ?view_as=subscriber

She also mentioned the links are wrong on the "Registration is Closed" message, but this may be out of scope? Not sure if worth changing since Registration is set to open 10/10 and that will go away

**Comment by stenington** [comment] 2019-09-11 13:50
Yeah, let's call both places the social links need updating in scope for this ticket. We made those changes on the TF platform, it was an oversight not to include them here.

**Comment by stenington** [comment] 2019-09-11 20:28
Okay @rsgonzal I think all the social links have been updated

**Comment by rsgonzal** [comment] 2019-09-13 16:11
katy confirmed all looks good!

**Closed** 2020-01-31 18:13 UTC
Labels: 8 - Done, it-04, it-05
