### ISSUE TITLE
PLACEHOLDER: Update "Meet your Chapter Ambassador" section for students

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4561] opened 2024-03-06 15:14 UTC
- Personal summary was removed as a chapter ambassador field, which means it can't be displayed on the "Meet your Chapter Ambassador" section
- Put chapter info in header based on which chapter the student selects or is assigned to

**Comment by dboyer** [comment] 2024-06-26 17:16
Closing as a duplicate of #4814

**Closed by dboyer** 2024-06-26 17:16 UTC
