### ISSUE TITLE
Admin can not change email address for mentors [5?,?,?]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2239] opened 2019-10-03 19:33 UTC
As an admin, staging isn't letting us change the email address for mentors. We're clicking save changes but it doesn't record. Stays on the same screen. When changing student addresses it goes back to the previous page and is recorded.

**Comment by hellafitz** [comment] 2019-10-16 19:30
next step: @rsgonzal confirm if this true on production as well. If yes, check w/ Program team on how painful this bug is (if they've even noticed).

**Comment by hellafitz** [comment] 2019-10-22 21:19
@rsgonzal please update

**Comment by rsgonzal** [comment] 2019-10-23 22:31
This is happening on production as well. Checking in with program team to check severity.

Get this screen when I try to edit:
![Screen Shot 2019-10-23 at 3 28 44 PM](https://user-images.githubusercontent.com/22801026/67439081-21185900-f5aa-11e9-9810-308f2d05d9fc.png)

**Comment by rsgonzal** [comment] 2019-10-30 07:51
Team does not see this as an issue. They usually ask mentors to reset their own passwords

**Comment by sha11n** [comment] 2019-11-09 07:03
I managed to recreate this bug locally. I think this is what's going on: the "Mentor Type" field is silently failing a validation check; so the page is being re-rendered. The error isn't being displayed b/c the "Mentor Type" field isn't setup correctly. Also, because it's not setup correctly, the drop-down isn't pre-selecting the value that is already set. :confused:

As a work-around, I found that you can select the value for "Mentor Type" that was already selected/saved (this value can be viewed on the previous page), which will pass the validation check, which will then allow the new email address to be saved. Let me know if this makes sense, and if it works for you, @rsgonzal. :smiley:

Lastly, the PR to address this is here: https://github.com/Iridescent-CM/technovation-app/pull/2289. Let me know if this fixes the issue. :smile:

**Comment by sha11n** [comment] 2019-11-10 03:08
While looking at this bug and the code more (w/ about 0.4% more understanding of how everything works :blush: ), from what I'm experiencing locally, none of the form fields for the mentor's account (first name, last name, email, dob, gender) will be updated while "Mentor Type" is left as "Choose one...". Also, when I select a new 'Mentor Type', the new value isn't being saved. I wonder if it's b/c I don't have my local environment setup completely, or it could be b/c I'm doing it wrong! :joy: :rofl: Anyhow, fwiw, the PR i opened #2289 fixed both of these issues locally for me. :man_shrugging: :smiley:

**Comment by stenington** [comment] 2019-11-12 21:25
Thanks @sha11n, I'm experiencing something like you were, where nothing was saving and I just kept seeing the edit page over and over. I suspect something else was going on in production though, because the "Uh oh, something went wrong" page is our 500 page, I believe.

This one may be tough to fully diagnose without access to production logs, although it's clear there are problems even *without* worrying about the 500s.

**Comment by sha11n** [comment] 2019-11-13 07:08
I updated the PR (#2289) to address your feedback, @stenington. Let me know what you think! :smiley: 

I also ran into another issue. If an admin edits a mentor, and clicks "Save changes" and then uses the browser's back button, it goes back to the edit form, if the admin then clicks "Save changes" again, it will cause an error:
```
No route matches [POST] "/admin/participants/5"
```
I wonder if this is what's causing the 500 in production? I noticed the URL before the error (on the edit form) is: `... participants/5/edit#/`, I wonder if the `#` is causing the error? It also seems to be affecting all participants, not just mentors. This issue could be related to #2173. :sweat: :grimacing: :sweat_smile: :grin:

**Comment by stenington** [comment] 2019-11-14 16:52
Thanks @sha11n, yeah we're essentially living with the idea that the back button is off limits for now. 🙁 

I reread this ticket more carefully, and I'm seeing that the original description was the "page just keeps reloading" problem, and not the 500, so maybe it's okay not to worry about the 500 for now, as it could have been caused by some complicated sequence of clicks like you're suggesting.

Your new PR is surprisingly simple! There are lots of mentors though who **do not** have a mentor type, it must have been introduced in a later season of the program. So with that in mind, I think we might want to go with your suggestion of preserving the "Choose one..." and also displaying appropriate error feedback on that screen if the validation requirements aren't met. That way admins at least understand why the page just keeps refreshing and the fields they try to change don't persist.

**Comment by sha11n** [comment] 2019-11-15 06:41
Well that's a bummer about mentors who don't have mentor types set, that would have made things easier! :blush: :smile: Anywho, I updated the PR #2289 to put back the "Choose one..." prompt, and to also display the error messages, which it wasn't doing before either. Let me know what you think! :smiley:  @stenington

**Comment by rsgonzal** [comment] 2021-08-05 23:29
@shaunxp20 should we close this or try to fix? 😅

**Comment by shaunxp20** [comment] 2021-08-06 19:25
> @shaunxp20 should we close this or try to fix? 😅

![Why_not_both](https://user-images.githubusercontent.com/58957909/128561447-c09e270a-388a-4115-8014-6c8de73309ac.png)
😂 😂 😂 

I vote to fix it, and then close it! 😁

**Comment by shaun-technovation** [comment] 2023-06-13 18:21
This long standing issue has been addressed in #4013. 👍

**Comment by dboyer** [comment] 2023-06-20 17:50
Confirmed on QA that I was able to change the email address for a mentor.

**Comment by dboyer** [comment] 2023-06-26 23:21
Confirmed on production that I could change the email address on my test mentor account.

**Closed** 2023-07-05 19:11 UTC
Labels: bug, blocked, 2 - Plan
