### ISSUE TITLE
General Support & Bug Fixes

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3254] opened 2022-02-16 17:42 UTC
> Just a reminder, this issue should be fixed on QA too 👍 😄

thanks, shaun! so it is not giving me a check mark for submission type and additions. BUT it does take it away for my business plan 😩

_Originally posted by @rsgonzal in https://github.com/Iridescent-CM/technovation-app/issues/3235#issuecomment-1040784398_

**Comment by rsgonzal** [comment] 2022-03-04 22:07
BUG: downloading onboarded vs not onboarding mentors is giving wrong numbers

- Login as an admin on production
- Filter for non-onboarded mentors
- We see ~1700 accounts
- Export & Download the data
- Only ~1000 accounts are on the spreadsheet

@devkonrad maybe you can take a look at this issue for us! I can not seem to replicate it on QA, just Production

**Comment by devkonrad** [comment] 2022-03-04 22:13
> BUG: downloading onboarded vs not onboarding mentors is giving wrong numbers
> 
> * Login as an admin on production
> * Filter for non-onboarded mentors
> * We see ~1700 accounts
> * Export & Download the data
> * Only ~1000 accounts are on the spreadsheet
> 
> @devkonrad maybe you can take a look at this issue for us! I can not seem to replicate it on QA, just Production

Hi, @rsgonzal! Sure i can get it! I just guess that i dont have login and passowrd valid for production environment, You can provide that credentials to me (on slack)

**Comment by devkonrad** [comment] 2022-03-07 14:18
> BUG: downloading onboarded vs not onboarding mentors is giving wrong numbers
> 
> * Login as an admin on production
> * Filter for non-onboarded mentors
> * We see ~1700 accounts
> * Export & Download the data
> * Only ~1000 accounts are on the spreadsheet
> 
> @devkonrad maybe you can take a look at this issue for us! I can not seem to replicate it on QA, just Production

I did some local tests and i find out that the export job query is limiting ro 1000 results, although this is not explicit in the code. Sometimes there is some default constraints limitations of the framework/orm i guress tha it can be the case. Im investigating more about that.


![Captura de tela de 2022-03-07 11-12-26](https://user-images.githubusercontent.com/99268176/157051432-ce8f4ac4-9d75-4c52-8320-a619739cbaeb.png)

**Comment by devkonrad** [comment] 2022-03-08 14:38
Hi! I got the information about the default queries on rails limit, it need to be setted by env
Reference here: https://edgeguides.rubyonrails.org/configuring.html
![Captura de tela de 2022-03-08 11-35-52](https://user-images.githubusercontent.com/99268176/157259665-77f5f6f5-e88b-470c-b8e4-4ab1a69e4f95.png)
.

**Comment by devkonrad** [comment] 2022-03-09 16:38
Hi! I'm still working on mentors bug. Turns out that the problem looks like a counter/list query problem. But i got other stranger thing (for me), the mentor graph dont sum 100% (13% + 10%). Is that correct?
![Captura de tela de 2022-03-09 13-30-15](https://user-images.githubusercontent.com/99268176/157487503-778873bf-1e4a-40aa-b9d9-a21cd9b085de.png)

**Comment by dboyer** [comment] 2022-03-09 17:01
There are definitely known issues with the charts on that admin page. I can't find the GH issue with the exact problem but @rsgonzal likely knows.

**Comment by rsgonzal** [comment] 2022-03-10 01:18
#2341 is the ticket with the graphs

**Comment by devkonrad** [comment] 2022-03-10 12:36
> #2341 is the ticket with the graphs

Thanks, @rsgonzal !

**Comment by rsgonzal** [comment] 2022-03-10 22:58
- [ ] pitch and demo video links should open in a new tab 

![Screen Shot 2022-03-10 at 2.55.52 PM.png](https://images.zenhubusercontent.com/60527169cde2772242d0de95/a6097ab4-9f1d-42c7-87ec-ce92a632c8ac)

**Comment by dboyer** [comment] 2022-03-15 14:07
Update: the team that works with mentor data is no longer experiencing the issue with downloads. We're going to pause work on the data downloads task for now as we are unable to recreate the issue on QA and it appears to no longer be an issue on prod.

**Comment by dboyer** [comment] 2022-04-20 16:54
On submissions, the email address fields for Thunkable and MIT App Inventor are no longer required. We should either:

- Remove the field from the front-end and mark it as non-required so that users can submit an app without it

OR

- Keep the field visible but make it non-required

Either option is fine and whichever is quicker can be selected. NOTE: Due to other pressing concerns, we should spend no more than a couple hours on this and bail out if it becomes more complex than expected.

**Comment by devkonrad** [comment] 2022-04-20 20:16
Remove the email validation for Team Submission: https://github.com/Iridescent-CM/technovation-app/pull/3359

**Comment by dboyer** [comment] 2022-04-21 18:45
Confirmed the optional email field is working as expected on QA

**Comment by dboyer** [comment] 2022-04-22 14:51
A few requests for label changes based on QA testing:

- [ ] On the admin page for submissions, rename the "screenshots" option under "more columns" to Images. If an admin adds the column "Missing submission pieces," pictures are listed as Images in the list so renaming screenshots to images keeps everything consistent.

<img width="593" alt="Screen Shot 2022-04-22 at 10 12 07 AM" src="https://user-images.githubusercontent.com/516764/164731757-a108ee20-3080-4e17-9d14-2152fa2f8b12.png">

- [ ] On submission admin page, rename "App name" and "App description" columns to "Project name" and "Project description"

<img width="843" alt="Screen Shot 2022-04-22 at 10 14 00 AM" src="https://user-images.githubusercontent.com/516764/164732134-02c04a88-c4bf-4aa6-8ec9-754812d825d7.png">

- [ ] Adjust the text by the App inventor and Thunkable emails to include optional. So: "What is the email address of your team's Thunkable account (optional)?" and "What is the Gmail address of the App Inventor account that your team is using (optional)?

<img width="667" alt="Screen Shot 2022-04-22 at 10 51 34 AM" src="https://user-images.githubusercontent.com/516764/164739202-f6545327-46ce-4a9c-bf07-88e6e6ea4c0c.png">

**Comment by devkonrad** [comment] 2022-04-22 18:02
> * Adjust text on user adoption plan field in the submission process to read: Submit your 1 to 2 page user adoption plan as a PDF file.

Placed a PR to address these changes: https://github.com/Iridescent-CM/technovation-app/pull/3365

**Comment by dboyer** [comment] 2022-04-22 21:24
Confirmed these changes are correct on QA

**Comment by dboyer** [comment] 2022-05-11 17:11
Closing and will add future bugs to new issue

**Closed by dboyer** 2022-05-11 17:11 UTC
Labels: bug
