### ISSUE TITLE
LearnWorlds Leftover Tasks

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#3192] opened 2021-12-10 22:03 UTC
Just jotting down some notes for the leftover stuff from #3037:
* Handle expired access token
* Email address issues - maybe these all are already solved?
* Write some tests
* Some code clean up

Probably all lower priority stuff at this point, just making a note so we don't lose track of these things.

**Comment by dboyer** [comment] 2023-05-31 17:04
@shaun-technovation Anything to do here since you're in the Learnworlds code? If not, should we close this?

**Comment by shaun-technovation** [comment] 2023-06-23 19:51
> @shaun-technovation Anything to do here since you're in the Learnworlds code? If not, should we close this?

Okay, finally getting around to addressing these outstanding things:

> * Handle expired access token

I don't think this is an issue, from memory we haven't seen any errors due to an expired token. We also have some code that will refresh the token if there is a LearnWorlds error, I think we're good here.

> * Email address issues - maybe these all are already solved?

This was an issue with using the `+` trick in an email address:
https://github.com/Iridescent-CM/technovation-app/issues/3037#issuecomment-987309356

I found this in an email to LearnWorlds support:
> During testing we use a lot of accounts with (+x), for example I would use roxana+mentor126@example.org to create an account on our platform. When trying to hit our SSO integration button, I get bounced back to our site. The error being returned from LearnWorlds is: {:code=>nil, :context=>"email", :message=>"already exists"}. After this error occurs, we are unable to perform a successful SSO call. However, I do see an account was created on Learn Worlds and I am able to use accounts with the (+x) on your site. Do you know why these accounts are causing this error on the initial SSO attempt? After an account is created on LearnWorlds, is it possible to use the email address again to perform SSO? How do we get these accounts passed this "email already exists" error?

And this was part of their response:

> As they informed us, the first issue you mentioned was indeed spotted and it has been resolved by our engineers.
So everything should be working properly regarding this.

----

> * Write some tests

I wrote some tests to give us some general coverage of the LearnWorlds functionality, there definitely could be more specific test cases we could add, but this is at least better than nothing!

> * Some code clean up

The code seems fine to me and it seems to be working as intended; I did make a minor change to make testing easier though.

**Comment by dboyer** [comment] 2023-06-26 23:17
I don't believe there is anything to test here. Confirmed that as a student on both production and QA I could click from the curriculum pages on the platform to Learnworlds and access the lessons.

**Comment by shaun-technovation** [comment] 2023-06-27 16:17
> I don't believe there is anything to test here. Confirmed that as a student on both production and QA I could click from the curriculum pages on the platform to Learnworlds and access the lessons.

Thanks for testing this! I did make some minor changes to the code (besides adding tests), so always good to make sure it's still working as intended. 👍

**Closed** 2023-07-05 19:11 UTC
