### ISSUE TITLE
Restrict access to "Chapter Admin Activity" until ChA is fully onboarded

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4419] opened 2024-01-17 14:29 UTC
Disable (or hide?) the "Chapter Admin Activity" link until after a chapter ambassador is fully onboarded.

**Comment by dboyer** [comment] 2024-01-17 14:32
Slight preference to disable rather than hide so that the ChAs know the additional functions will be available at some point and we don't have to field questions about where to go.

**Comment by dboyer** [comment] 2024-06-21 14:45
Closing as a duplicate of #4689

**Closed** 2024-06-21 14:45 UTC
Labels: 🗣 Discuss ✋, 🏖 Chapter Ambassadors ⛺️, AmeriCorps, ChA Onboarding, 📋 Chapters 📙
