### ISSUE TITLE
General support and QA fixes

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#3115] opened 2021-11-17 18:53 UTC

**Comment by shaunxp20** [comment] 2021-11-18 17:38
I'm running into a weird bug regarding back-end validation errors surfacing on the front-end; I've run into a situation where it's locking up the Next button. Investigating and trying to fix it now! :smiley:

**Comment by shaunxp20** [comment] 2021-11-18 23:21
> I'm running into a weird bug regarding back-end validation errors surfacing on the front-end; I've run into a situation where it's locking up the Next button. Investigating and trying to fix it now! 😃

I pretty much redid how we're enabling/disabling the Next buttons. Let me know if anyone sees any issues around the Next button being enabled or disabled when it shouldn't, and if this happens which field was last active and any details about it please! 😁

**Comment by rsgonzal** [comment] 2021-11-23 02:46
- can not create a team
- if i try to submit my media consent without actually signing, it blows up

**Comment by shaunxp20** [comment] 2021-11-23 02:49
From our QA spreadsheet:

> At the end of registration I got an error message saying ""Something went wrong saving your profile
Account gender can't be blank
Mentor type can't be blank"" -- shouldn't this happen on the first page before I can click next?

I will make both of these fields required on the form. 👍 😃

**Comment by shaunxp20** [comment] 2021-11-23 03:01
Re: required fields and disabling the Next button. I think it can be confusing that the Next button can be disabled (b/c not all of the required fields have been filled out), but you don't why the button is disabled b/c you don't know which fields are missing/required. Maybe we should turn back on "live" errors" or add an asterisk or something that let's people know a field is required? 🤔 ✅ ❌ 🧐

**Comment by shaunxp20** [comment] 2021-11-23 03:28
From our spreadsheet:

> 1 - When I click "full term of use" on the data use page, I was sent to a completely blank page and couldn't navigate back to my registration. I had to refresh the page then got brought back to the beginning and had to redo it all

I updated the link to point to: "https://iridescentlearning.org/terms-of-use/", which is where our current registration flow links to. I also made it so that it will open in a new tab/window.

> 2 - I was able to click next without agreeing to the terms of data use (it did pop up again after I got to my dashboard, but in the old branding) 

I made the data terms required now (so you can't click Next w/o agreeing to them).

**Comment by shaunxp20** [comment] 2021-11-23 15:43
> can not create a team

I need more details/repro steps for this one - I was able to create a team; just a hunch, this issue might be b/c of a parental consent and/or location issue. it might not be worth investigating too much either b/c it might just resolve itself too as we iron out more post-registration stuff. 😅 😄

**Comment by rsgonzal** [comment] 2021-11-23 17:20
> Maybe we should turn back on "live" errors" or add an asterisk or something that let's people know a field is required? 🤔 ✅ ❌ 🧐

i like the asterix, i think that's common practice?

**Comment by rsgonzal** [comment] 2021-11-23 17:27
> I need more details/repro steps for this one - I was able to create a team; just a hunch, this issue might be b/c of a parental consent and/or location issue. it might not be worth investigating too much either b/c it might just resolve itself too as we iron out more post-registration stuff. 😅 😄

I'm logged in as Rolo Dog and have my location and parent consent signed and i still can't create a team 🤔

**Comment by shaunxp20** [comment] 2021-11-24 00:05
Random note, we should QA #3026 to see if it's still an issue.

**Comment by dboyer** [comment] 2021-11-24 15:48
> Random note, we should QA #3026 to see if it's still an issue.

Updated on #3026 with more details. TLDR; it's not ideal but works currently and I don't think we need to do any work here prior to launch.

**Comment by shaunxp20** [comment] 2021-11-24 19:03
> i like the asterix, i think that's common practice?

I added some code that will automagically add an asterisk next to each "label" for a required field - this worked for all fields (afict) except for the mentor summary b/c it doesn't have a label, so I had to manually add that one to the description paragraph part. Anywho, it's on its way to QA now! 😄

**Comment by rsgonzal** [comment] 2021-11-25 02:35
I *think* the issue with team creation is related to a beginner student trying to create the team.

Seems to be ok when i tried an older student

**Comment by shaunxp20** [comment] 2021-11-26 16:59
> I _think_ the issue with team creation is related to a beginner student trying to create the team.
> 
> Seems to be ok when i tried an older student
> 
> Didn't happen for a returning beginner student. Throwing a wild guess that it's related to email 🤔🤔

Yes, you're right!!! Great catch on this! There was another parent/account email address validation (that wasn't updated to accommodate for the beginners division) that was failing which was preventing the team from being created! It was a super tricky one to debug since there wasn't much to go off of. Strangely, we have three separate parent/account email address validations, used for various things. 🤯 Refactoring all of this so it's in one spot would be nice, but Sweet Brown said it best, "Ain't nobody got time for that!". 😃 Anywho, I wouldn't be surprised if we run into other weird bugs like this. 😕

**Comment by shaunxp20** [comment] 2021-11-29 18:38
RE: (from our spreadsheet) parent email being locked on the last page when parents are signing up- we could hide this field entirely for parent accounts and just have the password field, would make it less confusing, imho. #RandomThought 😃

**Comment by dboyer** [comment] 2021-11-29 19:21
> RE: (from our spreadsheet) parent email being locked on the last page when parents are signing up- we could hide this field entirely for parent accounts and just have the password field, would make it less confusing, imho. #RandomThought 😃

I think any changes to this can wait until after launch. It's not ideal, but since it's working, we can wait on hiding this field or otherwise adjusting the email/password process.

**Comment by dboyer** [comment] 2021-11-29 20:57
Confirmed can now create a team with a parent/beginner account

**Comment by shaunxp20** [comment] 2021-11-30 17:21
We were getting a "You don't have permission to go there" message after registering, I addressed that in #3110, after the work for that (in #3160) gets merged in, we should be good! 🤞 😃

**Comment by rsgonzal** [comment] 2021-11-30 18:27
it looks like i can't register a team with the same name as a past season. not sure if this has always been the case though or if it matters..

**Comment by rsgonzal** [comment] 2021-11-30 20:48
> it looks like i can't register a team with the same name as a past season. not sure if this has always been the case though or if it matters..

scratch this. we want to keep it as is. might run into more trouble with urls and such

**Closed** 2021-12-02 22:10 UTC
Labels: 🏖 new-registration ⛺️
