### ISSUE TITLE
RA's Assigning Teams to Judges

### ISSUE THREAD

**Issue by kmorton2017** [Iridescent-CM/technovation-app#2126] opened 2019-04-29 19:29 UTC
I assigned all of my teams to judges from the **teams icon** on the Events page. I was not able to reproduce the error easily . 

I tried a different case scenario and assigned half of my teams to judges from the “teams” icon on the Events page.  I assigned other half to judges from the **“judges” icon** on the Events page. 
I logged out and back in again. All of my team assignments had been erased on my display.
I logged back in again. All of my team assignments were on display properly. It seems to sproadically not show assigned teams/judges. Sometimes it will disappear, and other times it will not. 

as a judge assigned to this event, i am able to still view my assigned teams. it does not appear to impact the judge from my testing so far. 

Below is the original problem description from the RA which I investigated: 
_"We assign judges to teams and when we come back, they are gone. We are not sure if they are only not loading, or they are gone for good...it seems to be a display issue only, but sometimes it takes a long time for them to appear again. It seems worse if you go straight to judges without opening the teams first (in the event). team assignments for invited judges (not registered yet) really disappear, those are gone for good"_

@stenington

**Comment by stenington** [comment] 2019-04-30 17:49
What I've found is that if you load the events page and click "Manage teams" first, you will see the judge assignments and you can switch back and forth from "Manage teams" and "Manage judges" without losing them.

If you refresh the page and click "Manage judges" first, you will **not** see the judge assignments, and if you switch back and forth between "Manage teams" and "Manage judges" they will not show up.

The cause is a typo in the code introduced 8 months ago. A variable name has been mistyped, and I guess we didn't do thorough enough QA to catch it 8 months ago when it happened. 😦 

I think that's the only problem though, so I'll put up a fix and ask @kmorton2017 to verify soon.

**Comment by stenington** [comment] 2019-05-01 15:43
@kmorton2017 a fix for this is in staging, you should not have the same trouble with judge assignments. Can you QA or write up the steps you want someone else to take?

**Comment by ophelieh** [comment] 2019-05-02 20:13
@stenington Looks like it works good now. Thanks!

**Closed by ophelieh** 2019-05-02 20:13 UTC
Labels: 5 - Test <= 8, Bug Priority - 1, Feature request
