### ISSUE TITLE
Handling student/mentor combo accounts [40,13,3.08]

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2354] opened 2020-01-22 16:10 UTC
From #2107:

> We have about 60 of those in production, 26 of those in the 2020 season. I think we saw problems with student/mentor combo accounts last year, and if I'm remembering correctly we began asking students who wanted to be mentors to create new accounts. I think there's a lot of logic in the platform assuming that a user will never be both a student and a mentor, so updating it to make that work right would be a lot of effort.

### To DOs
1. When an admin clicks the button to convert a Student account into a Mentor account, the conversion process should delete the Student account once the Mentor account is created.
- Confirmation message on delete popup: "You're about to convert [student name] to be a mentor. This Student profile will be deleted."
2. Add some sort of a 'Converted_from_[Student]' flag to the user account.
3. Delete the Student profile for any student who ALSO has a Mentor profile (should be 60 such profiles, more if additional conversions have happened recently)
4. Remove the patch we put in recently to stop these dual profile from receiving multiple emails to the same email account - #2606

## QA STEPS

As an admin:
* Find a student that is 14 years or older (for a ChA a student has to be 18 years or older to able to be converted to a mentor)
* View their profile
* Click the "Convert to mentor" button
* Verify the student profile has been deleted, verify the new "former student" flag that gets displayed now (we can change that text/color)
* See if issues in these tickets are still problems: #2648 #2649 #2650

There is a script that we'll run to delete the student profiles of existing student/mentor combo accounts. This dataclip will show which student profiles will get deleted for QA and production:
[https://data.heroku.com/dataclips/rewkmzutmstqqcbnemppgeimbkhj](https://data.heroku.com/dataclips/rewkmzutmstqqcbnemppgeimbkhj)

* We can run this script on QA, and verify some of these accounts look good afterwards
* Another good test scenario to check (for the manual conversions or via the script) would be for students who are on a team, to make sure the team looks okay afterwards; also it would be good to check that other parts of the system are working okay (student profiles are referenced in quite a few places in the code (300+ matches))

## DEPLOYMENT NOTES

For QA:
> heroku run bundle exec rake remove_student_profiles_of_mentors --app technovation-qa

For Production:
> heroku run bundle exec rake remove_student_profiles_of_mentors --app technovation

**Comment by stenington** [comment] 2020-08-28 01:55
@rsgonzal @hellafitz Flagging this for your attention since it came up again in #2606.

**Comment by rsgonzal** [comment] 2020-08-28 19:07
Thanks, mike!

**Comment by rsgonzal** [comment] 2020-09-17 00:20
This is coming up a lot. I also noticed another bug where these combo accounts are still showing up when filtering for students.

**Comment by rsgonzal** [comment] 2020-10-21 05:36
From TF/TG

> Option 2: delete past student profile
- Program Team track when we use conversion button - name, email, accountid, profile type?
- Program Team backs up each season all users on spreadsheet  (participant type, all columns, etc) before the season rolls over
- Conversion button on admin

**Comment by hellafitz** [comment] 2020-10-21 20:03
Deliverables:
1) When an admin clicks the button to convert a Student account into a Mentor account, the conversion process should delete the Student account once the Mentor account is created
2) Delete the Student profile for any student who ALSO has a Mentor profile (should be 60 such profiles, more if additional conversions have happened recently)
3) Remove the patch we put in recently to stop these dual profile from receiving multiple emails to the same email account

**Comment by rsgonzal** [comment] 2020-10-21 20:08
@rsgonzal get updated text saying will delete student profile & maybe log in whatever sheet
![Screen Shot 2020-10-21 at 1 00 34 PM](https://user-images.githubusercontent.com/22801026/96776917-84e08800-139e-11eb-919d-0bef7b67dfb6.png)

**Comment by hellafitz** [comment] 2020-11-05 20:36
Confirmation message: "You're about to convert [student name] to be a mentor. This Student profile will be deleted."

**Comment by rsgonzal** [comment] 2021-02-02 02:11
Noting these tickets as some things we will want to check in QA
 #2648, #2649, and #2650

**Comment by shaunxp20** [comment] 2021-02-02 19:54
Just documenting some of the weirdness about the "New/Returning/Past XXX" labels when viewing a converted student/mentor in the admin area.

I confirmed that when converting a student that participated in a previous season, they will get labeled as a "Returning mentor". That's because the system doesn't know how they participated (as a student, mentor, judge, etc.) for each season, it just sees them as participating in more than one season (so they get labeled as "returning").

And they will also get tagged w/ the new label "Former student" (we can change that label of course).

**Comment by shaunxp20** [comment] 2021-02-02 20:00
> Noting these tickets as some things we will want to check in QA
> #2648, #2649, and #2650

Thanks for bringing up this tickets! Fwict, it looks like #2648 and #2649 will get fixed w/ this, but we can confirm when it gets to QA. We'll see about #2650, but I'm pretty sure that one will need some more digging into. 😃

**Comment by shaunxp20** [comment] 2021-02-11 22:43
This one finally made it's way to QA, some QA steps have been added too. 😅 😁

**Comment by kate-technovation** [comment] 2021-02-19 21:43
1. As an admin, found a student that is 14 years or older: 
<img width="860" alt="Screen Shot 2021-02-19 at 4 38 06 PM" src="https://user-images.githubusercontent.com/57409606/108564276-d9562e80-72d0-11eb-8497-c5a8ceca00a8.png">

2. Viewed their profile:
<img width="905" alt="Screen Shot 2021-02-19 at 4 38 45 PM" src="https://user-images.githubusercontent.com/57409606/108564357-f0951c00-72d0-11eb-8b71-157476095505.png">
3. Clicked the "Convert to mentor" button:
<img width="528" alt="Screen Shot 2021-02-19 at 4 39 31 PM" src="https://user-images.githubusercontent.com/57409606/108564489-2fc36d00-72d1-11eb-9427-28804621025e.png">

4. Clicked "Yes" button to confirm:
<img width="543" alt="Screen Shot 2021-02-19 at 4 39 46 PM" src="https://user-images.githubusercontent.com/57409606/108564515-3a7e0200-72d1-11eb-8c15-1538fd13fab2.png">

5. Verified the student profile has been deleted:
<img width="844" alt="Screen Shot 2021-02-19 at 4 42 05 PM" src="https://user-images.githubusercontent.com/57409606/108564619-68634680-72d1-11eb-87ee-9d352c31cd85.png">

6. Verified that the new "former student" flag that gets displayed now:
<img width="860" alt="Screen Shot 2021-02-19 at 4 43 14 PM" src="https://user-images.githubusercontent.com/57409606/108564748-96488b00-72d1-11eb-982e-58196919acd2.png">

**Comment by rsgonzal** [comment] 2021-02-25 18:46
Thanks @kate-technovation ! really helpful. i updated the last ticket with your notes!

@shaunxp20 thanks for running the script! Since it just deleted the student profile, these accounts shouldn't have the new flag, right?

**Comment by shaunxp20** [comment] 2021-02-25 19:23
> @shaunxp20 thanks for running the script! Since it just deleted the student profile, these accounts shouldn't have the new flag, right?

Ah yes, the script will just delete the student profiles. I can update the script to add the flag too though, would be pretty easy. 😄

**Comment by rsgonzal** [comment] 2021-02-25 20:02
Maybe we should do that? Just so we don't have only a portion of them with the flag!

Also,
I've got a bug, but I'm not sure if it's related to this. I was thinking maybe the teams had someone with a combo account and something broke? I might be overthinking, but checking in!
BUg: Can’t click on newteam or mymentorteam
https://technovation-qa.herokuapp.com/admin/team_submissions#/
Saw somewhere else that new team deff has a full team of students and mentors

Other than that, things look good!

**Comment by rsgonzal** [comment] 2021-02-25 21:13
> Also,
> I've got a bug, but I'm not sure if it's related to this. I was thinking maybe the teams had someone with a combo account and something broke? I might be overthinking, but checking in!
> BUg: Can’t click on newteam or mymentorteam
> https://technovation-qa.herokuapp.com/admin/team_submissions#/
> Saw somewhere else that new team deff has a full team of students and mentors
> 
> Other than that, things look good!

Ok, yes! I think this is what's happening. I just converted Roxana Mail who was a student on My team's name. And I can no longer click on that team. But I don't think this will be a problem on production?

**Comment by rsgonzal** [comment] 2021-02-25 21:15
Wait now i can click on new team

**Comment by shaunxp20** [comment] 2021-02-25 21:22
> Wait now i can click on new team

Regarding newteam - I just fixed that one about 5 or so minutes ago. There was a join request to "North Dakota" who used to be a student (and now is a mentor), the student profile has been deleted, so that's causing the error, doh! I deleted the join request so the team can be viewed now (but that join request isn't being displayed anymore).

> Ok, yes! I think this is what's happening. I just converted Roxana Mail who was a student on My team's name. And I can no longer click on that team. But I don't think this will be a problem on production?

I think it could possibly be a problem on production (if there are join requests like this), I'm still investigating.

Good catch on this!

**Comment by rsgonzal** [comment] 2021-02-25 21:27
Wooo ok! Let's fix then. It was caught cause of exploratory QA, so guess it's a good thing I let this sit for a while 😅

**Comment by shaunxp20** [comment] 2021-02-25 22:21
> Maybe we should do that? Just so we don't have only a portion of them with the flag!

Okay, I made this change (so the script will add the flag), once it's on QA I'll run the script again.

> Wooo ok! Let's fix then. It was caught cause of exploratory QA, so guess it's a good thing I let this sit for a while 😅

Okay, I have a hacky fix for this to display those join requests (for converted students -> mentors). We could also delete these join requests (when we delete the student profiles), but I thought it would be better to display them for historical context. Anywho, it would be easy to just remove them altogether if we want to do that. 😄 

I'll let you know what this is all on QA! 😄

**Comment by shaunxp20** [comment] 2021-02-25 23:09
Just found another edge case, if a student sends a join request to a team, then the student is converted to a mentor (while the join request is still pending), then when a student of that team goes to "My Team" it will cause an error b/c it's trying to lookup the pending join request of the student profile that is now deleted. Seems unlikely to happen in production, but we should probably address it. Maybe the solution here is to delete pending join requests when students are converted to mentors? I think it would be weird to show a join request from a student who is no longer a student. 🤔 

Also, there's probably more cases like this, I'm still trying to find more.

**Comment by shaunxp20** [comment] 2021-02-25 23:25
Ok, I re-ran the script on QA, so all those existing student/mentor combo accounts should have the new flag now. 👍 

And you should be able to view those teams in the admin now too. 👍

**Comment by rsgonzal** [comment] 2021-02-26 00:42
Yay! Thanks, Shaun!

> Maybe the solution here is to delete pending join requests when students are converted to mentors? I think it would be weird to show a join request from a student who is no longer a student. 🤔

This sounds vvery reasonable! Let's do it. Do you think we should do it as part of this or just pass this one along as is?

**Comment by shaunxp20** [comment] 2021-02-26 16:51
> > Maybe the solution here is to delete pending join requests when students are converted to mentors? I think it would be weird to show a join request from a student who is no longer a student. 🤔
> 
> This sounds vvery reasonable! Let's do it. Do you think we should do it as part of this or just pass this one along as is?

It was pretty easy so I just went ahead and did it (deleting pending join requests when converting students to mentors), it'll be on QA sometime later today. 🤹 📆 😄

**Comment by shaunxp20** [comment] 2021-02-26 22:05
> It was pretty easy so I just went ahead and did it (deleting pending join requests when converting students to mentors), it'll be on QA sometime later today. 🤹 📆 😄

Btw, this fix is on QA now. 😄

**Comment by rsgonzal** [comment] 2021-03-01 18:19
hey @shaunxp20 how should i test this last part?

**Comment by shaunxp20** [comment] 2021-03-01 22:58
> hey @shaunxp20 how should i test this last part?

The change I made was to delete pending join requests when students are converted to mentors. I think what I did to discover the bug would work:
- as a student, request to join a team (leave this join request as pending), then convert them to a mentor
- as someone else on the team, view that team: My Team -> Students, verify this page works - it was causing an error prior this fix

**Comment by rsgonzal** [comment] 2021-03-01 23:16
ok looks good!

**Comment by shaunxp20** [comment] 2021-03-03 00:59
This one has finally been deployed! Thanks for your help getting this one across the line @kate-technovation @rsgonzal!!! 😃 🥳 🙌 🎉

**Closed** 2021-03-19 00:26 UTC
Labels: 8 - Done, [theme] registration, it-39, it-40, it-41, it-42, tech upkeep
