### ISSUE TITLE
Country data missing from Teams section

### ISSUE THREAD

**Issue by ophelieh** [Iridescent-CM/technovation-app#1789] opened 2018-10-31 17:58 UTC
**Describe the bug**
I was looking at teams from 2018, and then 2019 but the country doesn't show. I can see everything else though. 

**To Reproduce**
1. Go to 'Teams' 
2. Go to 'Seasons'
3. Select '2018' or '2019'
4. Add 'country', 'city' in More Columns
5. Click Search 
6. See error - countries do not show up (except for Hong Kong it seems) 

**Expected behavior**
I should be able to see countries. 

**Screenshots**
![image](https://user-images.githubusercontent.com/32206421/47808478-78277d00-dd0c-11e8-9dc4-a01fce33bab1.png)

**Desktop (please complete the following information):**
 - OS: Microsoft
 - Browser chrome
 - Version 70.0.3538.77

**Comment by ophelieh** [comment] 2018-11-09 21:07
I just checked and country is actually missing for all years, even the current one.

**Comment by adrichey** [comment] 2018-11-09 21:13
It appears that the county is set for the teams (this can be confirmed by clicking through to view the team), but it just isn't appearing in this view.

**Comment by ophelieh** [comment] 2018-11-12 17:43
Good to know! :)  But we do need to be able to see the country when we download the cvs. Do you have an idea of why it might not be showing up? 

Thank you!

**Comment by adrichey** [comment] 2018-11-12 20:03
No clue at the moment, but I can look into it for you. I agree that having that data appear is important. As soon as this bug is prioritized and brought into a sprint, I will look into it. :)

**Comment by Allicolyer** [comment] 2019-01-30 22:00
This appears to no longer be an issue. I will close this card.

**Comment by Allicolyer** [comment] 2019-01-30 22:02
@ophelieh is this a big priority?

**Comment by ophelieh** [comment] 2019-01-30 23:02
I don't think it's a priority but we will need to be able to download the team data including their country at the end of the season.

**Comment by Allicolyer** [comment] 2019-01-30 23:07
Good point @ophelieh actually, this will be critical to haven selecting semi-finalist and finalists. Because of that I am going to pull this card into this sprint.

**Comment by adrichey** [comment] 2019-02-04 19:59
This is now ready for testing. This was also a bug in other sections of the admin UI, so I fixed those while I was in there as well. You will want to make sure Country and State columns work for Participants, Judges, Events, Submissions and Teams views as well. Thanks!

**Comment by nickiredescent** [comment] 2019-02-04 20:18
Tested: State and Country are visible columns for Participants, Judges, Events, Submissions and Teams views

**Closed** 2019-02-04 21:09 UTC
Labels: 5 - Test <= 8, Bug Priority - 2, [sprint topic] admin / RA, [sprint topic] judging, bug
