### ISSUE TITLE
Add Chapter links to admin chapter view

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4681] opened 2024-04-29 21:40 UTC

**Comment by dboyer** [comment] 2024-05-15 18:03
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4681?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by shaun-technovation** [comment] 2024-05-21 18:30
This is on Preview.

I wasn't sure if the links should be clickable or not; they are, but it would be simple to remove that if we don't want them clickable.

**Comment by dboyer** [comment] 2024-06-02 15:16
Confirming that I now see the chapter links in the admin view of the chapter details. 

@shaun-technovation I'm fine with having the links be clickable, but it looks like right now the link is appended to the existing preview URL so there's an error page when you click the link. For example, the link to LinkedIn in the screenshot below goes to /admin/chapters/linkedin.com/technovation and gives an error page.

<img width="457" alt="Screen Shot 2024-06-02 at 11 13 20 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/8357e31a-e788-47d4-b1b3-4dd207796982">

**Comment by shaun-technovation** [comment] 2024-06-03 19:55
@dboyer When you get a moment, which ChA/chapter is this for?

**Comment by shaun-technovation** [comment] 2024-06-03 20:15
Nevermind^ I was able to reproduce this locally, I have a fix headed to Preview shortly. Good catch on this!

**Comment by shaun-technovation** [comment] 2024-06-03 21:04
> it looks like right now the link is appended to the existing preview URL so there's an error page when you click the link.

This should be fixed on Preview now. I also rebased Preview against QA, so Preview is up-to-date w/ QA now too.

**Comment by dboyer** [comment] 2024-06-06 17:15
Confirming that these links now open as planned.

**Closed** 2024-08-15 14:36 UTC
Labels: AmeriCorps, 📋 Chapters 📙
