### ISSUE TITLE
Salesforce auth token and caching

### ISSUE THREAD

**Issue by dboyer** [Iridescent-CM/technovation-app#4361] opened 2023-12-05 02:33 UTC
As part of #4321, testing was done using personal auth tokens. We'll need to work with the marketing team to get a generic login account on Salesforce and add automatically refreshing and caching the auth token for when it expires.

**Comment by dboyer** [comment] 2023-12-06 15:02
Liz is setting up an account for engineering@

**Comment by shaun-technovation** [comment] 2023-12-08 20:58
After this gets merged into QA, the "Salesforce <--> platform" pipeline will be complete. Currently, first name, last name, and email address are the only things being sent through the pipeline, future work will consist of adding more fields.

One thing I'd like to revisit is how contacts in Salesforce are updated, right now it's via their `salesforce_id` (I was basically following the README for the restforce gem). But I'm thinking it would be better to update them via email address (how our Mailchip integration works now). This way, we don't have to worry about how to get everyone's `salesforce_id` into the platform. And also, if parents are going to be separate contacts (like they are now in Mailchimp), we wouldn't have to add/track a `parent_salesforce_id`. Anywho, this would all be behind the scenes changes.

Another thing to mention when this gets to QA and we start testing it. After we see that it's working, I'd like to try removing admin permissions for the Salesforce account for this integration, I don't think this account needs admin permissions.

And lastly, for future reference, from the oodles of tabs I had open to work on this integration, here are ones that were most helpful:
- https://medium.com/@bpmmendis94/obtain-access-refresh-tokens-from-salesforce-rest-api-a324fe4ccd9b
  - I followed this pretty closely, most of the settings I added/changed were from here
- https://salesforce.stackexchange.com/questions/40346/where-do-i-find-the-client-id-and-client-secret-of-an-existing-connected-app
- https://trailhead.salesforce.com/trailblazer-community/feed/0D54V00007T4IlOSAV#ext-gen89
- https://documentation.sailpoint.com/connectors/identityiq8_3/salesforce/help/integrating_salesforce/generating_refresh_token.html

**Comment by shaun-technovation** [comment] 2023-12-12 18:56
The Salesforce integration is now on QA. All newly registered accounts should be added to Salesforce automatically (with their first name, last name, and email address). If their first name, last name or email address is updated, it should also get updated in Salesforce. When I was testing this myself, I couldn't find the accounts I was adding w/ my personal Salesforce account, I had to use the one for the Salesforce integration (credentials are in the password manager), maybe there's some kinks to be ironed out there, not familiar with Salesforce enough to now what's going on.

A few other notes, a nice to have and ideal feature to have would be a sandboxed Salesforce environment, so we're not adding to production. Since we don't have this yet, after we're done testing on QA we'll want to turn off the integration on QA. Also, regarding the client id, client secret and refresh token for the integration, I added those to our password manager. These are a part of our local settings too, we'll want to be careful about sharing these settings because the Salesforce integration account has access to everything on production.

**Comment by shaun-technovation** [comment] 2023-12-12 19:02
> we'll want to be careful about sharing these settings because the Salesforce integration account has access to everything on production.

I added #4382 to address these ENV settings and also to address/clean up the ENV settings in general.

**Comment by shaun-technovation** [comment] 2023-12-13 19:56
A few more notes.

I added all the Heroku config settings to both QA and Production already.

A random note regarding Heroku config settings:

From the [Heroku documentation](https://devcenter.heroku.com/articles/config-vars#managing-config-vars):
> Whenever you set or remove a config var using any method, your app is restarted and a new release is created.

From what I'm seeing, this is working as expected. I see a deployment updates in our Slack channel after making a change to one of the settings.

I think why sometimes the expected changes aren't being reflected on the platform is when they're used by Vue.js. The Ruby on Rails side seems to work as expected, but since they also get used in Vue.js (they flow from Heroku to Ruby on Rails then down to Vue.js), I think that's when it's not working as expected. Something to do with the config setting not getting updated in Vue.js. Just something to keep in mind for when the config changes aren't working as intended, I think it's when it's in the Vue.js world.

> One thing I'd like to revisit is how contacts in Salesforce are updated, right now it's via their salesforce_id (I was basically following the README for the restforce gem). But I'm thinking it would be better to update them via email address (how our Mailchip integration works now). This way, we don't have to worry about how to get everyone's salesforce_id into the platform. And also, if parents are going to be separate contacts (like they are now in Mailchimp), we wouldn't have to add/track a parent_salesforce_id. Anywho, this would all be behind the scenes changes.

I created #4385 to address this.

> a nice to have and ideal feature to have would be a sandboxed Salesforce environment, so we're not adding to production. 

I created #4386 for this.

**Comment by shaun-technovation** [comment] 2023-12-18 18:10
The Salesforce integration has been disabled for QA, to enable it again, in Heroku we'll need to add: `ENABLE_SALESFORCE` with a value of `1` or `true` should work too.

**Closed** 2024-01-24 17:41 UTC
Labels: AmeriCorps, Salesforce
