### ISSUE TITLE
Show official/unofficial event status to RAs [8,8,1]

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2378] opened 2020-02-13 11:45 UTC
Currently, all events are official when created. Admin has the ability to toggle them unofficial if they do not meet the event requirements

RAs are not given this information on their dashboards.

Proposal: When an event is toggled un-official by admin, show messaging on the RA event page telling them their event is un -official. 

![Screen Shot 2020-02-13 at 3 52 58 AM](https://user-images.githubusercontent.com/22801026/74432962-5aecc400-4e14-11ea-868c-89a46ad02f41.png)

Unknown: How to provide messaging for official events 
- After a certain date, all events not toggled un-official will replace above text with text that says "this event is an official event and will be scored)
- Program team just provides messaging that if they don't see if their event is un-official, then it is

**Comment by stenington** [comment] 2020-02-14 18:21
Similar to #2377, as a counter-proposal we could show **Status: official/unofficial/pending, check back on...** to RAs on the event in their dashboard. They probably don't need extra clarification on what those things mean, that's communicated to them through training or somewhere like that.

**Comment by stenington** [comment] 2020-02-14 18:22
We would need the actual date, which we agree could be hardcoded at this point.

**Comment by rsgonzal** [comment] 2020-02-18 20:34
@stenington April 22nd is the date.

**Comment by stenington** [comment] 2020-02-20 15:43
@rsgonzal What do you think about timezone issues here? April 22nd isn't the same set of 24 hours around the world, and if we want the platform to automatically do something different after a certain time, I think we need a specific date and time, including timezone.

**Comment by stenington** [comment] 2020-02-20 21:53
I think we have to make the date configurable to test this. Otherwise there's no good way I know of to make staging think it's after the finalization date to see that display.

**Comment by stenington** [comment] 2020-02-24 14:29
### QA steps

The relevant config settings here are
* `DATES_RPE_OFFICIALITY_FINALIZED_YEAR`
* `DATES_RPE_OFFICIALITY_FINALIZED_MONTH`
* `DATES_RPE_OFFICIALITY_FINALIZED_DAY`

**With config set to a date in the future, relevant to when you're testing...**

1. log in as an RA
2. create an event
3. you should see **Status: pending** on your event

**With config set to a date in the past, relevant to when you're testing...**

1. log in as an RA
2. create an event
3. you should see **Status: official** on your event
4. as an admin, mark the event as unofficial
5. as the RA again, you should see **Status: unofficial** on your event

**With config set to the date on which you're doing the testing...**

1. log in as an RA
2. create an event
3. you should see **Status: pending** on your event

The config is essentially setting the last day on which "pending" will still be shown. It should switch to showing the actual status after midnight of the configured date, Pacific time, but I'm not really expecting anyone to QA that. 😄

**Comment by rsgonzal** [comment] 2020-02-25 17:36
Works as expected!

Ran into the same issue with time zones. Nick's Taiwan RA could see the status on today's date. Team said this wouldn't be an issue though!

**Comment by stenington** [comment] 2020-02-25 17:45
That actually worries me a bit, because this ticket shouldn't be doing any timezone conversion. Let me look into it.

**Comment by stenington** [comment] 2020-02-25 22:04
Okay, I was wrong. This took me down a bit of a time zone rabbit hole.

It turns out that for RAs (and only RAs) we override `Time.zone` for the app to the `timezone` stored on their account. That means for this ticket that the deadline is shifted to their time zone, so if the deadline is the 25th and it's the 26th in Asia but the 25th in the US, RAs in Asia will see event statuses while RAs in the US will not.

[This article](https://thoughtbot.com/blog/its-about-time-zones) was helpful in understanding some of the details.

One of the confounding problems here is that dates don't carry timezone information like times do, which makes everything a bit more confusing in the code.

**Comment by stenington** [comment] 2020-02-25 22:25
I know the program team was okay with the RPE statuses becoming available for eastern timezones first, but I want to make sure the code is written to clearly communicate what should be happening so when we come back next year and say "Oh yeah, what are the details of this setting? When exactly will the switch happen?" hopefully it's not a huge pain to determine. I'm opening a follow up PR to try to address that, which I think will end up changing the semantics of this date from being the last day that statuses will be pending to being the first day that statuses are considered final and can be shown.

**Comment by rsgonzal** [comment] 2020-02-26 01:06
Interesting! Sounds good. So do we need to hold off on this ticket until we work on the other one? Or can this move forward?

**Comment by stenington** [comment] 2020-02-26 15:28
I'd like to do it in this ticket, the PR is open. If @shaunxp20 sees big problems with the approach in the PR maybe we take a step back and turn it into future work.

**Comment by stenington** [comment] 2020-02-26 17:56
@rsgonzal I think we've got it so all RAs will see their event statuses starting at the same time (e.g. a Taipei RA won't see it before a US RA) and the config doesn't change from how you tested it the first time. The date specified is the last day "pending" will be shown, until 11:59pm Pacific.

It would be great if you could do a second round of QA though (whether you involve the program team again or not is up to you) once it's on staging. The QA steps previously defined are appropriate to follow again.

**Comment by rsgonzal** [comment] 2020-02-27 00:53
Is this on staging?

If I'm understanding correctly, a Taiwan RA should NOT see their status before a US RA? This is not currently true..

**Comment by shaunxp20** [comment] 2020-02-27 00:56
> Is this on staging?

Looks like it hasn't made it to staging yet. 🌞 🌟 🌝

**Comment by rsgonzal** [comment] 2020-02-27 01:02
thanks, @shaunxp20 ! makes sense :sweat_smile:

**Comment by stenington** [comment] 2020-02-28 15:16
@rsgonzal The fix for this is on staging. I created an RA in Auckland, NZ where it's currently the 29th, set the officiality finalized date to the 28, and my Auckland RA sees their event as "pending" so I think this is now working as intended, but would love for you to give it a look as well.

**Comment by rsgonzal** [comment] 2020-02-28 16:58
Just checked it and it looks to be working as expected!

**Closed** 2020-04-14 00:25 UTC
Labels: 8 - Done, [theme] events, it-16, it-17
