### ISSUE TITLE
BUG: If a current student on a team is converted to a mentor, Admin are unable to manage that team (platform errors out)

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4574] opened 2024-03-14 18:33 UTC

**Comment by viviancan** [comment] 2024-03-14 18:51
Based on [this thread](https://iridescentlearning.slack.com/archives/C06CHBQ4E/p1710427643287059)
If a student is on a team, then that student is converted to a mentor, we are unable to manage the team (delete current team members).

**Comment by viviancan** [comment] 2024-03-14 18:57
To confirm the current bug on QA

1. Find a team with at least 2 students in 2 different divisions 
2. Convert the older student to a mentor
3. Confirm the division is still the division of the older student
4. Try to delete the remaining student
5. Platform should error out

@dboyer listing these bug steps for an extra set of eyes!

**Comment by viviancan** [comment] 2024-03-14 19:00
I confirmed these steps on QA with the team [Flowers Forever](https://technovation-qa.herokuapp.com/admin/teams/633?allow_out_of_region=true#!division)

I converted the older student (senior division) Wild Kratss to a mentor. The flowers Forever team is stuck in "senior" division even though the remaining student is a beginner. I tried to delete the remaining student and the platform errored out

**Comment by dboyer** [comment] 2024-03-14 20:24
Confirming that I see the same bug when I follow these QA steps. I also got an error page when I tried to edit the team's name or summary as an admin.

**Comment by viviancan** [comment] 2024-03-14 21:32
Confirming the update is on QA and working as expected

**Comment by dboyer** [comment] 2024-03-15 14:27
Tested on QA and confirmed:

- I added a senior student to Yellow Submarines, a team with only beginner students
- That team then became listed as in the senior division
- I converted the senior student to be a mentor
- The senior student who is now a mentor was automatically removed from the team
- However the team is still listed as in the senior division
<img width="784" alt="Screen Shot 2024-03-15 at 10 20 45 AM" src="https://github.com/Iridescent-CM/technovation-app/assets/516764/69c08c82-061e-4113-b4a3-b661690b7ba7">
- I edited the team's summary and when it saved, it refreshed the team as a beginner division team

I repeated this process with the team "Kittens are the Best." So it looks like an edit is needed to refresh the division. I think that's okay but just noting that will be part of the process. @viviancan

**Closed** 2024-03-20 16:37 UTC
Labels: bug
