### ISSUE TITLE
Show assigned RPE to judge on dashboard

### ISSUE THREAD

**Issue by joemsak** [Iridescent-CM/technovation-app#1447] opened 2018-02-26 21:31 UTC
Judge is assigned to live event - should see pertinent details

Judge is not assigned - should see that they will judge virtually

**Comment by kmorton2017** [comment] 2018-03-21 19:39
judges who did not complete their on-boarding were not able to see the RPE details until they completed their tasks. is it possible for a judge who is assigned to an event to see these details? 

for all judges who are not onboarded, under the "score submissions" it could say you need to complete your required steps before viewing submissions. Quarter final judging begins May 1st. 

also i noticed that if a judge was onboarded, they were actually able to click the "start submissions" button and begin judging.  (that won't be live until May 1st right?)

confirmed that judges not assigned to an RPE saw they were a virtual judge. 

confirmed that judges assigned to a live event could see pertinent details if they were fully onboarded.

**Comment by joemsak** [comment] 2018-03-21 20:01
Thank you @kmorton2017 please check again in about 15 minutes for all of these issues being addressed

Leave your judge not onboarded and turn judging on to test that they will not see the "start a score" link

**Comment by joemsak** [comment] 2018-03-22 14:03
@kmorton2017 can we please get this wrapped up today?

**Comment by ophelieh** [comment] 2018-03-22 19:38
It all works great. 
A not onboarded virtual judge -  did not see the "start a score" link. 
An not onboarded judge invited to a RPE - was able to see details 


![uploads/f85aaadd-984d-4d2b-851d-5f1fb814caa0/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Ff85aaadd-984d-4d2b-851d-5f1fb814caa0%2Fimage.png)

**Comment by kmorton2017** [comment] 2018-03-22 20:50
@ophelieh do you think its confusing to see this line? 

"If your Regional Ambassador invites you to a live event, you will receive an email, and details will appear here." ie there are hundreds of judges are not going to be invited to a live event

**Comment by ophelieh** [comment] 2018-03-22 21:42
@kmorton2017 I don't think it is, especially because it is in another color. It might be more confusing not to have it, and judges who know they are going to attend RPEs might ask us why they see "online judging" (if they haven't been invited to the event at that time).

**Comment by joemsak** [comment] 2018-03-22 21:50
@kmorton2017 @ophelieh check the updated text on QA now, see if it's clearer

**Comment by ophelieh** [comment] 2018-03-22 21:54
Looks good to me.

**Comment by joemsak** [comment] 2018-03-22 21:57
thanks @ophelieh I'll await confirmation from @kmorton2017 as she was more concerned with the wording

**Closed** 2018-03-23 20:34 UTC
Labels: 5 - Done, [sprint topic] events, [sprint topic] judging
