### ISSUE TITLE
Add a custom link for inviting students to your team and make findable in dashboard

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-app#2677] opened 2020-09-18 18:14 UTC
Could add a custom link for invites (either individually or team-specific) so it could be dropped in chat or otherwise avoid email

**Comment by stenington** [comment] 2020-09-22 18:41
Is this the same as #2676?

**Comment by stenington** [comment] 2020-09-22 19:06
I was looking into the implementation of email invites a little, because they function similarly and I was hoping we could lean on them to provide a usable link as asked for.

The email that goes out includes two main parts: an `invite_token` and a `mailer_token`. The `invite_token` is used to look up the invitation, and the `mailer_token` is used to log in the desired mentor if they aren't already logged in when they click the link.

My thought is that the shared link could be the same url shared in email, minus the `mailer_token`. We would also need to update the invitation functionality to be more picky about the logged in mentor. That way if the link were accidentally shared in a public channel, it would still only allow the intended mentor to accept or decline their invitation.

**Comment by hellafitz** [comment] 2020-09-23 07:20
This was a duplicate of 2676. I've closed that one.

**Comment by hellafitz** [comment] 2020-09-23 18:06
Qs: 
- Should this be specific to students, or do we make something equivalent for mentors? Currently you can't add a mentor by email. Most mentors have an account already. 
- Is the invite link restricted to a specific email? Not yet. It should be.

@bagomer would appreciate any thoughts you have on this. No rush.

**Comment by hellafitz** [comment] 2020-10-09 18:29
@bagomer bumping this up. It's under consideration for the next iteration and we'll be refining it on the student side. Good to know if it's be useful or not on the mentor side.

**Comment by bagomer** [comment] 2020-10-12 16:18
I think this would be useful for mentors to be included in this functionality. I personally like the interation of a team reaching out a mentor's provided email.

**Closed** 2022-02-16 22:30 UTC
Labels: Discuss, 2 - Plan
