### ISSUE TITLE
Certificates: Add ability for admin to delete certificates

### ISSUE THREAD

**Issue by stenington** [Iridescent-CM/technovation-app#2073] opened 2019-03-29 20:22 UTC
**Is your feature request related to a problem? Please describe.**
Add the ability for an admin user to delete a certificate for an end user.

**Describe the solution you'd like**
I'd like the ability for admins to delete certificates from the system. There's a chance that we already have bad certificates in the system, or that the wrong certificate could be generated for someone, and admins should be able to address that. I'm imagining the ability to delete a certificate would live somewhere on the Certificates datagrid, either in the datagrid itself or after clicking through to a detail view, TBD.

**Additional context**
This work should happen after the work for #2057 has been completed.

**Comment by adrichey** [comment] 2019-04-01 14:33
@stenington I was thinking that I might put the certificate deletion on the participant view in the certificate list, but it dawned on me that this would only be displaying 2019 certificates. So I am thinking it might be better if it is added to the datagrid at this point. Where did you envision this being added? If you can let me know, I will get started on this.

**Comment by stenington** [comment] 2019-04-01 15:08
Well, I was hoping to copy a deletion pattern from somewhere else in the admin, but the only one I've seen is for suspicious scores where you get the buttons at the bottom of the score page:

![Screen Shot 2019-04-01 at 11 06 19 AM](https://user-images.githubusercontent.com/55319/55338248-4ad32c80-546e-11e9-9147-46660763e3c7.png)

Is it overkill to create an entire `show.html.erb` template just for a delete button?

**Comment by adrichey** [comment] 2019-04-01 15:45
Hmmm. Maybe not? It could always be improved later on to display the PDF in the browser as a preview or something. I think that is a good approach. I can work on that page. I will basically just provide a link or download button for the certificate on that page and an additional deletion button as well. If that sounds good, I think I will stop work on #2062 as it is a bit more nebulous and start in on this.

**Comment by stenington** [comment] 2019-04-01 15:51
Sounds good to me

**Comment by adrichey** [comment] 2019-04-02 15:05
This is now ready for testing. Acceptance Criteria:
1. Log in as an Admin
2. Browse to Certificates in the dashboard side-navigation
3. Click the PDF icon in the View column for a certificate
4. Confirm that you are brought to a screen where you can view the certificate, and delete it
5. Deleting a certificate should provide you with a confirmation pop-up where you can confirm or cancel the confirmation
6. Make sure you can delete a certificate

**Comment by kmorton2017** [comment] 2019-04-02 21:12
I confirm the steps outlined above @adrichey

**Comment by ophelieh** [comment] 2019-04-05 21:27
@nickiredescent Could you test this?

**Comment by nickiredescent** [comment] 2019-04-08 17:08
Tested. Works as described. Can confirm that as an admin, I am able to delete certificates with a warning prior to confirmation.

**Comment by ophelieh** [comment] 2019-04-08 17:39
@nickiredescent Did you try to say don't delete (or no/yes) when getting the warning? Just want to make sure we have that covered as last season when deleted a student, if you pressed that button by accident and tried to cancel, it would still delete the student. Thank you!

**Comment by nickiredescent** [comment] 2019-04-08 17:52
I've tried the delete button out, both yes and no. This works as intended and the profile was not deleted from the platform.

**Comment by adrichey** [comment] 2019-04-08 18:11
Thanks @nickiredescent! Marking this as closed then. 🙂

**Closed by adrichey** 2019-04-08 18:11 UTC
Labels: 5 - Test <= 8, Feature request, [sprint topic] scores / certs
