### ISSUE TITLE
Name validation during registration

### ISSUE THREAD

**Issue by shaun-technovation** [Iridescent-CM/technovation-app#4911] opened 2024-08-07 22:01 UTC
- Prevent someone from entering a period for their first or last name
- Require at least one alpha character

**Comment by dboyer** [comment] 2024-08-21 17:53
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Technovation-605271851956b1000ec2f24d/issues/Iridescent-CM/technovation-app/4911?planning-poker) with Zenhub @shaun-technovation @viviancan

**Comment by dboyer** [comment] 2024-09-13 14:22
Tested on QA and confirmed:

- I had to enter an alphabetical character (no punctuation or numbers) when registering as a student
- When I edited my profile, it failed if I tried to include only a punctuation mark, number, or something else that was a non-alphabetic character

@shaun-technovation Two potential things:

- When I tried to register as both a student and mentor, I tested entering just A as my last name. I got a message I needed to add an alphabetical character. If I make the character into a lower case a, I no longer get that message. <img width="1440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2JUQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--30b4f4af5ff4d7eb5f7c2889fa79dd98704852a4/Screen%20Shot%202024-09-13%20at%2010.19.05%20AM.png" alt="Screen Shot 2024-09-13 at 10.19.05 AM.png" />

- It looks like it's reading accented characters as non-alphabetical characters. Is it possible to change that? <img width="1432" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL25UQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2933f998799c48e305417f3bab9b2afdd2d175fe/Screen%20Shot%202024-09-13%20at%2010.20.47%20AM.png" alt="Screen Shot 2024-09-13 at 10.20.47 AM.png" />

Based on the accented character issue, I wonder if this name validation will also prevent people entering non-Roman characters. I know we have some Arabic and Cyrillic characters that people have added.

**Comment by dboyer** [comment] 2024-09-18 14:15
Confirmed on QA that I could register when I entered an upper case letter as the single character in the first or last name fields.

**Comment by dboyer** [comment] 2024-09-23 15:41
Moving this back to in progress as we've determined that we do want to support non-Roman alphabetic characters in the name fields.

**Comment by dboyer** [comment] 2024-09-24 21:23
Confirmed on QA that a single punctuation mark cannot be in the first or last name field.

@shaun-technovation It looks like accented characters can be a second character but not a single character. Is that accurate? Same for Cyrillic characters. If that's intentional for technical reasons, I think it's okay.

 <img width="1438" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWY4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d77a64a2cb59ee99be395bcda6880b246f4850d7/Screen%20Shot%202024-09-24%20at%205.20.48%20PM.png" alt="Screen Shot 2024-09-24 at 5.20.48 PM.png" />

<img width="1454" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWo4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d044f360c2ec3727b3666cb4ee49f5176a83974c/Screen%20Shot%202024-09-24%20at%205.22.40%20PM.png" alt="Screen Shot 2024-09-24 at 5.22.40 PM.png" />

**Comment by dboyer** [comment] 2024-09-25 18:03
Tested on QA and I can now add a single character that is accented or in a non-Roman character set.

However, I was also able to add a single comma, plus sign, semicolon, question mark, etc in the field. The only punctuation marks that seemed to be restricted as a single character entered in the field were a period or a dash.

<img width="810" alt="Screen Shot 2024-09-25 at 2 03 37 PM" src="https://github.com/user-attachments/assets/b7478c8e-b1d6-4280-a7d3-31bd87891297">

**Comment by dboyer** [comment] 2024-09-25 21:24
okay - I checked with Sasha and she has only seen dash and period as the single punctuation mark to avoid putting in a name. I'm good with deploying this as is and we update later as needed.

**Comment by dboyer** [comment] 2024-09-26 15:49
Confirmed on production that I could not register with just a period or dash in the name fields. I could use a single accented character.

**Closed as completed** 2024-10-02 16:56 UTC
Labels: 🏖 New Registration ⛺️, AmeriCorps
