### ISSUE TITLE
Allow admin to view chapter program info responses

### ISSUE THREAD

**Issue by viviancan** [Iridescent-CM/technovation-app#4724] opened 2024-05-13 20:13 UTC

**Comment by viviancan** [comment] 2024-05-20 01:37
This is on Preview! Have a great week

**Comment by dboyer** [comment] 2024-05-20 14:52
Tested on Preview and confirmed:

- I see the link on the chapter admin page to view program info
- When I click that link, I see details of the chapter's program info
- Missing fields are marked as missing
- When a ChA updates the form, the updated details are visible on the admin page

@viviancan One note: I did not fill out the program start date or launch event dates, but in both the admin and on the participant's view, it said the start date and launch event date were today. It looks like both fields default to the current day if they are not edited. Can we keep them blank or mark them as "missing" as with the other fields so that PT doesn't assume the date was selected by the user. I split this out into #4738

**Closed** 2024-08-15 14:53 UTC
Labels: Added during iteration, AmeriCorps, 📋 Chapters 📙
